### ISSUE TITLE
MPI

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#1]
Trev:

Can we use the MPI for SciPy project to help build a better log capturing mechanism?  Might give us the interactive-real-time delivery we want.

**Comment by tclarke** [comment]
MPI is designed primarily for data transfer and coordination in distributed algorithms so I don't think it's the proper choice for logging. Remote system logging with rsyslogd or syslog-ng is probably a good option as existing syslog logging (Python logging module, etc.) will automatically go there with proper system config.

**Comment by tclarke** [comment]
See issue #15 for log changes.
