### ISSUE TITLE
Default rabbitmq configuration raises ACAS scan issues

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1005]
We need to investigate the clear text authentication defaults in our RabbitMQ deployed with Scale. Hopefully this is just a setting on the RabbitMQ container launch that will eliminate this issue.

**Comment by gisjedi** [comment]
Deployment of RabbitMQ is done here during bootstrap: https://github.com/ngageoint/scale/blob/master/dockerfiles/framework/scale/bootstrap.py#L288

RabbitMQ deployment JSON: https://github.com/ngageoint/scale/blob/master/dockerfiles/framework/scale/app-templates/rabbitmq.json

Docker image used for RabbitMQ deployment: rabbitmq:3.6-management
https://hub.docker.com/_/rabbitmq/
RabbitMQ docs need to be referenced for using more secure authentication scheme.

**Comment by Fizz11** [comment]
Others have had this issue with RabbitMQ as well:

https://groups.google.com/forum/#!topic/rabbitmq-users/t5lEc_-E410
https://support.solarwinds.com/Success_Center/Network_Performance_Monitor_(NPM)/AMQP_Cleartext_Authentication
http://thread.gmane.org/gmane.comp.networking.rabbitmq.general/49660

if the simple solutions suggested in the links dont work then TLS implementation may be necessary... 
https://www.rabbitmq.com/ssl.html

**Comment by gisjedi** [comment]
@Fizz11 What does this mean for complexity of the deployment? Does RabbitMQ have built in support for TLS and how do we configure the certificates? Are there any cert trust issues using self-signed certificates from a client perspective?
