### ISSUE TITLE
Scheduler Track Queued Executions

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#101]
Have the scheduler keep an in-memory data structure that tracks why the various queued job executions have not been scheduled yet. If an execution has not been scheduled for a certain threshold (time? number of scheduling passes?), then this information could be synced to the database to provide feedback to the users.

Eventually this information could be useful for capabilities such as scaling nodes up/down and estimating time to complete current job load.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
