### ISSUE TITLE
Secret configuration via DCOS Catalog packaging

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1015]
Presently we don't support configuration of Vault stored secrets as part of the DCOS configuration. We should add config.json entries to the DC/OS Catalog package.

Changes need to be made to config.json here:
https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/S/scale/5/config.json

Changes need to be made to marathon.json to consume here:
https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/S/scale/5/marathon.json.mustache#L26

**Comment by Fizz11** [comment]
updates included in pr https://github.com/mesosphere/universe/pull/1550
