### ISSUE TITLE
UI should pull from config at runtime

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#102]
Right now the UI pulls from the local config at build time. Update the UI to pull from the local config at run time. This is needed so we can configure a UI Docker container that already has the built UI.

**Comment by dev-geo** [comment]
Must need for any dynamic deployment using Marathon. Right?

**Comment by ericsvendsen-mil** [comment]
Moved configuration files to `/config` directory and converted them to JSON.  Angular now requests these files at runtime and integrates them into the app.  The local config file symlink on the destination server will need to be changed as well as the format of the local config file itself (see `/config/scaleConfig.local.json` for an example).  Once in place, modifying that local config file will affect the UI without needing to rebuild the project.

**Comment by ericsvendsen-mil** [comment]
Closed with #132
