### ISSUE TITLE
Scheduler Warnings/Errors

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1032]
Create a set of warnings and errors for the scheduler and system services similar to the ones for the nodes and add them to the status API.

Also add the scheduler state (and service state) the status API. Consider a degraded and/or a stopped/blocked state for the scheduler.

Change node state order to have scheduler stopped state come after node paused state.

Make a warning/error for when vault is closed and stop logging exception stacktraces when it is closed.

**Comment by JohnPTobe** [comment]
Dismissing the degraded/stopped/blocked state for the scheduler, all other issues are addressed in #1507 and other PRs.
