### ISSUE TITLE
Unify and organize documentation

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/scale#104]
There are currently a number of locations where documentation is found:

http://ngageoint.github.io/scale/
https://github.com/ngageoint/scale/blob/master/README.md
API documentation in the built tarball

It would be helpful to expose a single web accessible location with a brief overview, quick start guide, as well as the full API documentation built by Sphinx. The recommendation is to either use the existing gh-pages or something like readthedocs as the primary documentation hosting.

**Comment by icy-gisjedi** [comment]
Initial sample of hosting the documentation on readthedocs.org:

http://scale.readthedocs.org/

**Comment by dfaller** [comment]
Merged into master
