### ISSUE TITLE
Update scheduler to use Mesos HTTP v1 Scheduler API

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1040]
Update the scheduler to use the Mesos HTTP v1 Scheduler API.

**Comment by gisjedi** [comment]
This is being worked as a requirement of supporting DCOS Strict mode for some clients. Supporting Strict mode did not appear to be possible under the legacy protobuf interface. We are using mesoshttp PyPI package.

**Comment by gisjedi** [comment]
We must ensure that master failover is properly handled by our use of the mesoshttp package.

**Comment by gisjedi** [comment]
Short-term we are rolling the mesoshttp tarball into source, but once they release 0.3.0, we need to update our requirements to consume from official source. Ref: https://github.com/osallou/python-mesos-http/pull/6#issuecomment-436571556

**Comment by gisjedi** [comment]
https://github.com/osallou/python-mesos-http/releases/tag/0.3.0 out so #1415 is OBE
