### ISSUE TITLE
More algorithms

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#109]
Add more algorithms to our test/example clusters.

**Comment by dev-geo** [comment]
Where will these be hosted as containers and source code?

**Comment by tclarke** [comment]
We're currently storing some examples in the main github repo. We could have a separate repo for additional algorithms. As for containers, I plan to setup docker hub to auto build from master but I need to fix some build/deployment issues first.

**Comment by dfaller** [comment]
Merged into master
