### ISSUE TITLE
New v6 jobs API

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1113]
**Retrieve Jobs List** (replace what is currently there)
GET /jobs/
Query Params
- should be identical to the query params for the v6 /jobs/cancel/ and v6 /jobs/requeue/ APIs
- also add `is_superseded`, reworking `include_superseded` param so all jobs are returned by default (make `is_superseded` a normal filter field where specifying a value does filtering)
- also have `batch_id`, `recipe_id` (matches against `recipe_node` table), `job_type_name`, and `order` as before

Response 200 OK, use paged list, use v6 job serializer (fields below), order by `order` query param
- job_type (v6 base serializer)
- job_type_rev (v6 base serializer)
- event (v6 serializer)
- recipe (non-superseded recipe) (v6 serializer (base?), make sure recipe type base info is included)
- batch (v6 base serializer)
- is_superseded
- superseded_job (model ID serializer)
- status
- node (v6 base serializer)
- error (v6 base serializer)
- num_exes
- input_file_size
- source_started
- source_ended
- created
- queued
- started
- ended
- last_status_change
- superseded
- last_modified

**Comment by JohnPTobe** [comment]
Nevermind the non-superseded recipe part, that's going to be too expensive for a list.
