### ISSUE TITLE
Benchmark writes for small Scale jobs

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1118]
We need a way to benchmark nodes in order to debug node unhealthy states resulting from heavy churn of Docker containers.

**Comment by gisjedi** [comment]
We are able to force nodes into an unhealthy state, evidenced by Docker Daemon unresponsive errors, by heavy queuing of Scale Hello jobs. This can also be seen when a node is heavily taxed with many low resource consuming jobs during normal operations. The key to triggering the issue is to saturate the Docker daemon with container creations (>20 concurrent / node) and ensure this is repeated over multiple passes (at least 3 passes of maximum node capacity). Performance degradation appears to be related to IO bottlenecks as the `dockerd` process can be seen regularly entering 'D' state from a `top` view of node processes.

We need to understand what a proper IO benchmark is that will allow us to identify and mitigate this impact at the node level.

**Comment by gisjedi** [comment]
This post gives a great deal of detail that explains why we are likely encountering issues in AWS. We are using `gp2` instances. https://jeremyeder.com/2017/07/25/docker-operations-slowing-down-on-aws-this-time-its-not-dns/

**Comment by gisjedi** [comment]
Based on the inconsistent burst behavior of the GP2 type AWS nodes, we may just need to identify a target IOPS needed for processing. This would best be accomplished with a way to drop-in metrics collection. If we can accomplish this with cloudwatch, great, otherwise we should look at collectd for File IO metrics collection.

**Comment by Fizz11** [comment]
I've written up a wiki page detailing the steps we took to set up cluster monitoring, which also provides the means to monitor disk performance for any scale job. 

https://github.com/ngageoint/scale/wiki/Setting-up-cluster-monitoring
