### ISSUE TITLE
Look into gulp build problems

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#113]
gulp failed due to a missing module. npm didn't update and gulp didn't fail with the correct error so ansible thought everything succeeded. Look into these issues. Also look into cleaning up the UI build and extra scale copies (in dockerfiles, etc.) so these errors are more easily noticed.

**Comment by ericsvendsen-mil** [comment]
Which module?

**Comment by dfaller** [comment]
This issue is OBE.
