### ISSUE TITLE
v6 Strike REST API

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1143]
Create new v6 Strike REST APIs. There are no changes from v5. Create new v6 versions of all Strike-related JSON schemas. Look at changing POST /v6/strikes/ so that user does not submit *name* (Scale-generated instead from title). Add docs to new v6 section of the REST API docs.

**Comment by JohnPTobe** [comment]
auto generate name from title field, ignore user specified name if present.
write util for converting title to name that works like seed convention:
just lower case letters and dashes
limit to 30ish characters (whatever the database field allows)
append uuid if conflicts with another name
