### ISSUE TITLE
Clear out database update

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1149]
Clear out all of the updates in the database update system task. Users will need to have completed all of these updates in the most recent v5 release before moving to v6. Once Scale is at v6, we can assume that all of these updates have been completed.

Apply any needed database migrations that can occur now that the updates have been removed. For example, add a job_exe index (job_id, exe_num) and remove batch_job and batch_recipe models.

**Comment by JohnPTobe** [comment]
The database updates have been removed, we can add migrations to clean up the database accordingly.

**Comment by JohnPTobe** [comment]
What would we add a job_exe index for?  What would it do?

**Comment by JohnPTobe** [comment]
Is it related to #736?

**Comment by JohnPTobe** [comment]
There is already an index on job_exe but there are fields that were moved to the output and end models so they should be removed. Also, we should open another issue investigating the index being reversed in aws's rds (exe_num, job_id)
