### ISSUE TITLE
Remove legacy job types

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1155]
Remove the legacy job type capability so that only Seed-compliant job types can run. This will remove a lot of old code and simplify the job type logic. All Scale system jobs will need to be transitioned to have Seed-compliant interfaces.

This should result in the removal of (but not limited to) everything under:
job/configuration/data
job/configuration/interface
job/configuration/results
job/data
job/handlers
job/deprecation.py

Also remove job model methods that are no longer needed.

Remove v5 APIs for creating/editing job types and errors.

Place a logic check that does not allow the queuing of jobs with a legacy job type revision (don't throw an exception, just ignore queuing the job and log an error).

**Comment by emimaesmith** [comment]
Closed via #1534
