### ISSUE TITLE
Parse Scale file meta-data for Seed

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1160]
This issue represents updates to the parsing of Seed output file meta-data.

Parse meta-data side car files for input files if provided in the output directory in a directory/file name structure that matches input file(s). Only allow the setting of meta-data ONCE on a Scale file (log a warning). This replaces the old "parse results" capability in Scale.

The following meta-data fields (all found within `properties` member of GeoJSON object) are special and Scale will store them in indexed columns for files, jobs, and recipes for searching/filtering:
dataStarted
dataEnded
sourceStarted
sourceEnded
sourceSensorClass
sourceSensor
sourceCollection
sourceTask

The following meta-data fields are special fields added to the meta-data by Scale itself (both for input and output files):
"url": "http://..../file.txt"
"jobName": "foo"
"jobVersion": "1.0.0"
"packageVersion": "1.0.0"

After this issue is complete, searching by the defined source fields (sourceCollection, sourceSensor, etc) could be added to the /jobs/, /recipes/, and /files/ APIs (create new issues in v6 REST API project).

**Comment by gisjedi** [comment]
I'm not clear on what is intended by the phrase above:

> The following meta-data fields are special fields added to the meta-data by Scale itself (both for input and output files):

Are we intending to capture these properties from the optional _output_ metadata file and store somewhere? I certainly see their utility on input to give context to the executing job, but I'm failing to see why a job would ever need / want to specify those values as they are immutable from the job execution perspective.

**Comment by dfaller** [comment]
We don't capture these values, Scale generates them in the post task and adds them to the meta-data, so they will get saved with the products. The point is to store those values with the product meta-data to give additional info/context for each product.
