### ISSUE TITLE
v6 PATCH/POST Recipe Type REST APIs

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1178]
Create the new v6 recipe type REST APIs for creating/updating recipe types. Don't forget to update the v6 REST API docs!

**Edit Recipe Type**
PATCH /recipe-types/{name}/
- title
- description
- definition
- auto_update (bool, used to automatically update recipe types that contain this recipe type)

Response 204 No Content
If successful, this should result in a new recipe type revision with the new definition. Also make sure to clear/repopulate the `RecipeTypeSubLink` and `RecipeTypeJobLink` models. If `auto_update` is true, send an `update_recipe_definition` message for each recipe type that contains the edited recipe type.

Also add an `auto_update` field to POST /job-types/ to do the same thing, allowing users to automatically update the appropriate recipe types when a job type gets a new revision.

**Create new recipe type**
POST /recipe-types/
- title
- description
- definition

Response 201 Created, location header should point to recipe type details, return recipe type details body
This needs to automatically generate the `name` field similar to other v6 REST APIs.
Make sure to populate the `RecipeTypeSubLink` and `RecipeTypeJobLink` models.

**Validate Recipe Type**
POST /recipe-types/validation/
- name
- definition

Response 200 OK, see v6 batch validation for an example
- is_valid
- errors
- warnings
- diff (create a `RecipeDiff` between the current revision definition and new definition passed in, convert the diff to v6 JSON, strip schema version and return)

If the `RecipeDiff` indicates that the recipe type will not be able to be re-processed after the update (`RecipeDiff.can_be_reprocessed`), include a warning that mentions this.

**Comment by JohnPTobe** [comment]
Need to optionally have the recipe type name in validation for generating diff
