### ISSUE TITLE
Allow job types to specify additional data mounts

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#119]
All a job type definition to specify workspace locations to mount into the container for accessing DTED, reference imagery, etc.

Possibly allow inline file specifications as well so that common containers can easily provide algorithm specific config files, etc. without having to build a new container for each instance.

**Comment by cshamis** [comment]
Should all 'mounts' be workspaces?  Then it just becomes a job->workspaces[] list.

**Comment by gisjedi** [comment]
Mount implementation has been completed via https://github.com/ngageoint/scale/pull/773
