### ISSUE TITLE
local_settings.py modification for DCOS deployment

### ISSUE THREAD

**Issue by droessne** [ngageoint/scale#120]
I talked with Trevor about deploying Scale into DCOS. 

I believe we need to modify the local_settings.py to support Environment variables. This will make scale modifiable outside of the container as well as simplify the deployment of the containers into DCOS (Marathon). 

Trevor also made the suggestion of making the default local_settings.py support environment variables as well as exporting it as a volume so we can use it as we do today.

FYI: we do have a version of DCOS on DevNet that we can test with.

**Comment by tclarke** [comment]
This is OBE and has already been implemented in master.
