### ISSUE TITLE
v6 Purge Source File REST API

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1212]
Create a v6 purge source file REST API.

POST {'file_id': 1234} to /v6/files/purge-source/ - returns 204 No Content
API should return 400 if invalid or non-source file ID
Successful API call should send a purge_source_file command message to perform the purge.

**Comment by mikenholt** [comment]
This REST API call should create a `user` trigger event that is passed through messages.  It should be the event for the `scale-delete-files` system job.
```
description = {'user': 'Anonymous'}
event = TriggerEvent.objects.create_trigger_event('USER', None, description, timezone.now())
```
