### ISSUE TITLE
How to Create a Job

### ISSUE THREAD

**Issue by nevasway** [ngageoint/scale#1223]
I have Scale up and running on my cluster and I'm ready to test it out. How do I create my first job? Are there any references available?

I've searched the `Wiki` and the `Issues` to no avail. I've read through the documentation and found this section: https://ngageoint.github.io/scale/docs/cli/index.html but I think it's out of date. I apologize if I've missed something obvious but I need some help getting started.

**Comment by mikenholt** [comment]
Yep, the CLI stuff is out of date.  You want to be looking here: http://ngageoint.github.io/scale/docs/algorithm_integration/index.html

Feel free to hop into our gitter chat room to talk with a developer: https://gitter.im/ngageoint/scale

**Comment by mikenholt** [comment]
Answered in gitter chat.
