### ISSUE TITLE
Ensure the default algorithm error condition isn't system error

### ISSUE THREAD

**Issue by dev-geo** [ngageoint/scale#124]
Help differential between system and algorithm errors by ensuring algorithms don't default to "unknown" system error. Many quickly integrated algorithms don't return appropriate error codes and push the initial diagnosis to the scale/infrastructure team by reporting as system "unknown" error. Reserving system error for pre, post, etc. helps quickly diagnose problems and get the correct team assigned to fix data or algorithm error conditions. Once an algorithm is running the default would be better as ALGORITHM Unknown error.

**Comment by dfaller** [comment]
Create a new error:
ALGORITHM Error: General algorithm failure where no exit code mapping was provided

In description for error 3, include a high level explanation of defining exit code mappings for the algorithm to get better error reporting.

The job task should report this error when a failure occurs after a running update has already been received and a valid failure exit code has been provided, but the exit code does not have an exit code mapping.
