### ISSUE TITLE
Recipe Status Page

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#125]
We need a way to see (at a glance) the pass fail rates for all the recipes over a time period.  The metrics page can do just about anything with jobs, but we have little in the way of Recipe-level introspection.  Facts I think would be needed at minimums are:

Time date picker (for time range)
Percent complete:incomplete BY RECIPE 
Total bytes in by recipe (all inputs)
Total bytes out (products)
Total CPU hh:mm 
Latency in hh:mm (that's going to be meaningless for reprocesses, though) 
Maybe even some kind of candlestick chart for some of these values to indicate variance off mean.

We need to a way to see when (if) things are not completing without having to comb through page after page of jobs.

**Comment by dickmancj-mil** [comment]
[RecipeStatus-JobStatus-sketch.pdf](https://github.com/ngageoint/scale/files/202705/RecipeStatus-JobStatus-sketch.pdf)

Adding sketches of Recipe and Job status pages

**Comment by emimaesmith** [comment]
Closing as OBE
