### ISSUE TITLE
DCOS SDK integration

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1282]
Revisit use of the DCOS Commons SDK for deployment of the Scale components. The plan is to remove all bootstrap logic from the Scale container and defer this logic to the DCOS Catalog package. We are targeting the following deployment strategy:

- Package Scheduler
  - DB (optional)
    - Initialize (migrate / initial data)
  - RabbitMQ (optional)
  - Elasticsearch (optional)
    - Logstash (optional)
      - Web Server
      - Scheduler

**Comment by emimaesmith** [comment]
Closing due to LOE too high to provide value with current implementation.
