### ISSUE TITLE
Parse input file meta-data

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1289]
Parse meta-data side car files for input files if provided in the output directory in a directory/file name structure that matches input file(s). Only allow the setting of meta-data ONCE on a Scale file (log a warning). 

This replaces the old "parse results" capability in Scale. The current "parse results" capability still needs to remain intact.

Also fix the special `url` meta-data field that Scale sets on a product's or source file's meta-data. Right now the `url` appears to always be set to `null`.

**Comment by gisjedi** [comment]
It wasn't really anymore work to use the sidecar concept and didn't introduce another one-off. Adding data on source files can be done for an `INPUT_FILE` on the interface by writing to `$OUTPUT_DIR/INPUT_FILE.metadata.json`.
