### ISSUE TITLE
Optimize job filtering in UI

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale#1296]
Per conversation with @gisjedi and Shamis about how the Jobs page needs to be reworked to improve usability now that Scale has grown:

1) When a user clicks through to the Jobs page it should not query for default results.  This will allow the user to instantly filter for what they need without waiting for that first large query to return.  If a user does want to see ALL jobs for a time period they can filter for that and wait for the response.  Show a message that indicates that a filter needs to be set before results will be shown. 

2) Modify the current drop down list to be a combo box that provides the functionality of a drop down, with the added feature of typing in a `job-type`.  Include an option for all job types.  

3) Make the default time range 24 hours.  Add several buttons for popular time spans (24-hour, 3-day, etc.).  Also allow for the current ability to have a custom range set.

**Comment by emimaesmith** [comment]
Closing as the New Scale 7.x+ UI addresses these points.
