### ISSUE TITLE
Check for job type workspace in pre-task

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1321]
Presently, if a v6 Job Type is launched without a default workspace in the configuration, it reaches the post task and fails out on attempting to save any output files. 

We should validate that a workspace is properly set prior to queuing or in the pre-task.

**Comment by emimaesmith** [comment]
Part of this change incorrectly added a check to the scheduling manager _process_queue method. This check should be removed as the _process_queue is not the place to be checking for missing workspaces, and this check is already performed during the job pre-task.
