### ISSUE TITLE
Disable any trigger rules in v5

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1322]
In the interest of validating all triggered processing is migrated to new recipe of recipe functionality, we should add the ability to disable all trigger rules with the last 5.x release. This will allow administrators to identify any processing that has not been migrated to the new system.

This issues is related to https://github.com/ngageoint/scale/issues/1181

**Comment by emimaesmith** [comment]
Closing due to no more Scale 5 development (unless a major issue is discovered).
