### ISSUE TITLE
Bug in RecipeTypeDetailsV6 return

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale#1351]
https://github.com/ngageoint/scale/blob/bda54ba3a4e892ed39c18474ce2e694579b70c2f/scale/recipe/serializers.py#L78-L81

This line will always return empty as the old `interface` field was renamed to `manifest`.  I think `source=manifest` should be added but that is a much larger set of JSON and `manifest.interface` is likely what is desired.

**Comment by JohnPTobe** [comment]
Fixed by commit 815c442671cbe4f9fc0631ec1c9185b9cb58f64b
