### ISSUE TITLE
Remove old recipe code

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#1377]
After the trigger system is removed (requires #1181 to be completed), remove the following old recipe code:

 - deprecated `reprocess_recipes` message (and associated RecipeManager methods)
 - deprecated `update_recipes` message (and associated RecipeManager methods)
 - everything under recipe/configuration
 - everything under recipe/handlers
 - everything under recipe/seed
 - everything under recipe/triggers
 - recipe.deprecation

There should be a lot of TODOs to help guide you.

**Comment by emimaesmith** [comment]
Closed via #1534
