### ISSUE TITLE
Refactor log system

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#15]
Refactor the log system:
Remove all of the Django database logging (LogEntry model in Error app)
No longer include task logs in the database
Figure out a new method of log storage so that logs don't need to be moved once a task finishes
Store task logs independently (pre/job/post tasks)
See if stdout and stderr can be both combined and separated
Remove stdout/stderr columns in the database and figure out new columns for handling URLs that can be used for log viewing.
Update the JobExecutionManager.task_started() and JobExecutionManager.task_ended() methods and update the tasks to remove stdout/stderr and the URLs
Should this use the workspace system?

This is an important issue for improving the reliability and performance of the scheduler since logs will no longer have to be dealt with during status updates.

**Comment by tclarke** [comment]
I'm investigating an ELK stack which seems to be a go-to for docker container logging. Elasticsearch is a modern log structured nosql database. Logstash takes multiple logging inputs (stdout, stderr, syslog, etc.) and sends them to multiple outputs (stdout, elasticsearch, etc.). Kibana is a visualization tool for databases including elasticsearch.
The EL components might be a good option and K might work for arbitrary visualization but I suspect we'd replace that with a REST middleware and the standard scale UI. I'll post some additional updates here or on the chat system as I learn more.

**Comment by tclarke** [comment]
Docker 1.6+ offers logging plugins for stdout/stderr which can plug into logstash, remote syslog, AWS CloudWatch, json file, etc. https://docs.docker.com/engine/admin/logging/overview/ for more information

**Comment by wardcr** [comment]
A couple other options I saw discussed recently...
Apache Kafka: http://kafka.apache.org/
Twitter DistributedLog: https://twitter.github.io/distributedlog/html/
