### ISSUE TITLE
Add recipe and job "gannt-chart" to metrics

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#1533]
target for 7.3

**Comment by emimaesmith** [comment]
Goal would be to visualize the history of when a recipe type was activated until the last time it was ran ultimately in a timeline view. Recipe `is_active` changes should also be captured in the timeline data. Handling multiple versions of a recipe type will need to be considered.

Updates the metrics API will need to be made to return this information.

**Comment by mikenholt** [comment]
Query from Clint: 
![IMG_20190409_163936](https://user-images.githubusercontent.com/22593495/55833862-857c3b00-5ae6-11e9-9d7d-7fa3572c21e9.jpg):boom:

**Comment by emimaesmith** [comment]
Updated query to group results by recipe type and remove portions leftover from previous iterations of the query.

```
WITH day_periods AS
 ( SELECT (Date_Trunc('day', Now()) - ((days_ago - 2) * INTERVAL '1 day')) AS end_time,
          (Date_Trunc('day', Now()) - ((days_ago - 1) * INTERVAL '1 day')) AS start_time,
      FROM Generate_Series(1, 30, 1) days_ago
 )
SELECT to_char(d.start_time, 'YYYY-MM-DD') AS recipe_date,
             rt.Name                       AS recipe_type_name,
             Count(*)                      AS new_recipe_count
    FROM day_periods d
    JOIN Recipe r
    On r.Created BETWEEN d.start_time
                     AND d.end_time
    JOIN Recipe_Type rt
      ON rt.ID = r.Recipe_Type_ID
   GROUP BY d.start_time, rt.Name
   ORDER BY 2, 1;
```

**Comment by emimaesmith** [comment]
Gantt chart added to the UI via: https://github.com/ngageoint/scale-ui/pull/96

Closing this issue in favor of creating new, more specific, issues if additions/improvements are requested.
