### ISSUE TITLE
Duplicate Job Type Creation Attempt Returns 500 Error

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1562]
Creating a duplicate job type currently returns a 500 Server error. A 400 error should be returned with the proper error message.

**Comment by JohnPTobe** [comment]
The error actually occurs with a duplicate error model. We need to catch that and return a descriptive message if it is a legitimate duplicate. We also might have to de-duplicate errors created from manifests.

**Comment by JohnPTobe** [comment]
The actual problem is manifests with duplicate error names. We should update the validation code to mark such manifests as invalid.

**Comment by JohnPTobe** [comment]
See #1567
