### ISSUE TITLE
Create AWS Quickstart deployment scripts and documentation

### ISSUE THREAD

**Issue by dickmancj-mil** [ngageoint/scale#159]
Need to improve AWS QuickStart.  Evaluate Vagrant QuickStart vs. developing production-ready solution using CloudFormation.

Documentation should be complete and allow user to easily and reliably stand up AWS environment for dev, demo or production.

**Comment by gisjedi** [comment]
Superseded by #578

**Comment by gisjedi** [comment]
Quickstart documentation can be found here:

http://ngageoint.github.io/scale/quickstart.html
https://github.com/dcos/examples/tree/master/1.8/scale
