### ISSUE TITLE
Seed manifest with no output files will not validate 

### ISSUE THREAD

**Issue by Fizz11** [ngageoint/scale#1604]
A seed manifest with no output files will validate and run properly within the seed CLI, however when creating a new job-type in scale the manifest MUST contain at least an empty output file set or it will not validate properly. 

ex. 
```
    "outputs": {
              "json": [
                {
                  "name": "output_1",
                  "key": "output_1",
                  "type": "string"
                }
          ]
      }
```
validates and runs with seed CLI but will not validate in scale unless 
```
"files":[]
```
 is added.

**Comment by gisjedi** [comment]
Clint just discovered that if you attempt to validate the following it fails with 500 error:

```
...
"outputs": {}
...
```
This is valid according to the spec, so we need to relax the validation to make both `json` and `files` members optional.
