### ISSUE TITLE
v6 batches don't override priority

### ISSUE THREAD

**Issue by wong-j** [ngageoint/scale#1645]
Submitting a v6 batch job using a configuration priority on the batch will not override the priority value of the job-type.  It will get inserted into the queue table as the default job-type priority.

**Comment by JohnPTobe** [comment]
I was finally able to reproduce this bug.  Jobs created from legacy job types will get the priority of the job type and that takes precedence over everything in the queue_jobs method.  As legacy job types have been removed along with the priority field of jobs, this is no longer an issue.
