### ISSUE TITLE
Cancel Jobs Bug?

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1666]
"Cancel of jobs didn't work"
Possible API bug. Have no information other than "didn't work". Investigation needed to see if this is API or UI related.

**Comment by mikenholt** [comment]
call Chris and get more details.

**Comment by mikenholt** [comment]
@cshamis can you provide more detail?

**Comment by cshamis** [comment]
I Tried canceling two runaway strike jobs.  I selected them from the jobs detail (which took over 30mins for them to show up) 

Then I clicked cancel.  The button pushed... but the jobs never canceled.  No error.  No confirm... no nothing.

So, that's all the detail I have.

**Comment by mikenholt** [comment]
I have been able to repeatedly cancel strike jobs with expected behavior when testing master on our local cluster. Closing for now but we can reassess if this issue persists on prem.
