### ISSUE TITLE
SILO_URL Doesn't Propagate to UI Deployment

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1709]
**Description**
The SILO_URL environment variable is not propagated down to the scale-ui deployment.

**Reproduction Steps**
Steps to reproduce the problem:
1. Deploy new scale container on DC/OS cluster (ensure SILO_URL is set under the scale environment variables)
2. View the scale-ui service environment variables and note SILO_URL is not one of them

**Expected behavior**
The SILO_URL value is passed down to the scale-ui deployment

**Version and Environment Details**
  - Scale API: v7.0.0-7.0.0rc4
   - Can be found at `/api/v6/version/`
 - Scale UI: v0.5.0
   - Can be found at the bottom of the UI interface.
Cluster details below are very helpful for problem resolution, but external Scale users aren't expected to provide.
 - DC/OS: 1.10.9 Enterprise
 - Marathonlb: 1.5.12

**Comment by gisjedi** [comment]
This is as designed. `SILO_URL` should _never_ be set up on the UI container unless you are wanting to skip the reverse-proxy and will likely cause CORS issues. `SILO_BACKEND` is the proper value and as far as I can tell, is being set correctly.  This is an inconsistency between the UI and the Scale variable and could be changed to clear up any confusion.

**Comment by emimaesmith** [comment]
Closing due to not an issue

**Comment by gisjedi** [comment]
Reopening to resolve inconsistency between Scale deploy and UI.
