### ISSUE TITLE
Containerize System Tasks

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#171]
This issue is for the refactor work associated with getting all Scale system tasks to run within Docker containers.

**Comment by dfaller** [comment]
Added a new JSON field called 'configuration' to the job model. It holds information about the workspaces and Docker params required by the job. This information is derived from the job's data when it is provided. A data migration was added to populate the new field for all job models with job data (this could be a very long migration!)

**Comment by dfaller** [comment]
Added job and configuration fields to the queue model so that the job and workspace information is known by the scheduler when it schedules queued job executions. A data migration was added to populate the new queue model fields from their already linked job execution.

**Comment by dfaller** [comment]
Added configuration field to the job execution model so it knows the workspaces and Docker parameters needed for each task. The old Docker param field and the deprecated pre_task_id, job_task_id, and post_task_id fields were removed from the job execution model.

**Comment by dfaller** [comment]
Refactored the broker and workspace system to be simpler and removed dependency on using the host's local file system to create directories for a job's input and output data. The input and output data will now reside within named Docker volumes that are passed from task to task.

**Comment by dfaller** [comment]
Added code for job executions to configure volume-related Docker parameters when the executions are scheduled

**Comment by dfaller** [comment]
Added Docker repository field to scheduler model and moved scheduler model creation to system initialization instead of through the fixture

**Comment by dfaller** [comment]
Instead of mounting in a local_settings.py file, Scale will now use environment vars to pass database connection information to system jobs and tasks. All system jobs and tasks have now had their properties switched to use Docker containers.

**Comment by tclarke** [comment]
Need to pull the system image before execution.
Need to remove failed containers.

**Comment by dfaller** [comment]
We're going to Mesos 0.25 soon and then pulling the images before the task launch is unnecessary.

Yeah, I don't know what cleanup we'll need to run. Mesos cleans up the old containers eventually, but I don't know if the named volumes will get cleaned up as well.

**Comment by dfaller** [comment]
Merged into develop
