### ISSUE TITLE
Pin recipe types on ID instead of name

### ISSUE THREAD

**Issue by wong-j** [ngageoint/scale#1711]
**Pain Point? Please describe.**
Recipe types currently allow names in addition to titles as part of the definition.  If a name already exists, it will append a guid and be accepted with no way to remove.

**Desired Solution**
Remove name from the recipe definition and use just the ID and Title.  User's shouldn't have to define both "My First Recipe Name" and "my-first-recipe-name".  Using ID as the unique key is much simpler.  Titles should be reusable since they will have a unique ID.  

**Alternative / Workaround**
Issue #1710 will block people from submitting existing names, but moving forward it doesn't needed to be blocked

**Comment by JohnPTobe** [comment]
The REST api only takes a title. The ui should be updated to remove the name field and duplicate names should be blocked (per #1710).  I think we should use just the generated name as the unique key without using the id. I don't like reusable titles as finding the right recipe in a list with identical or nearly identical titles would be incredibly annoying.

**Comment by JohnPTobe** [comment]
To be clear, I think the definition should stay the same as it is. The api needs to reject duplicate names.

**Comment by JohnPTobe** [comment]
Closing as this is the desired behavior.
