### ISSUE TITLE
Optimize Endpoint Response Creation

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1717]
**Pain Point? Please describe.**
Certain API endpoints can be slow to respond at times when returning large lists of results: Ex. filtering the results for the jobs page.

**Desired Solution**
The filtering on certain endpoints should be re-looked at to see if any optimization can be done to improve the responsiveness.

First reported in #1673

**Comment by mheppner** [comment]
JT, Mike probably already let you know the issue, but I'll add some details here in case he didn't. `/jobs` and `/recipes` are experiencing the `n+1` query problem, despite `select_related()` being applied in the query manager. Specifically, `job_type` and `job_type_rev` are being selected for each result in `/jobs`, and `recipe_type` from `/recipes` (I didn't see a query for `recipe_type_rev`). Removing those fields from the serializer removes the extra queries.

**Comment by mikenholt** [comment]
Mark did a very quick inspection of this last week. Here are his findings as it relates to the jobs and recipes pages (the two most important pages IMO): 

![Screenshot 2019-07-17 13 39 21](https://user-images.githubusercontent.com/22593495/61397644-5836ea00-a898-11e9-8785-507282e1a05c.png)
