### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale#1718]
**Pain Point? Please describe.**
When deprecating a job type and/or recipe type, recipe types that contain them are automatically deprecated (made inactive) if auto-update is set to true.  Users are not warned of this fact, however and it's hard to know which recipe types will be affected.  Scale should display a warning that this will occur and list affected recipe types so the user can correct them if needed.

**Desired Solution**
When a job type or recipe type is deprecated and auto-update is set to true, display a warning listing recipe types that will be affected.  This can be returned via a response from the patch api similar to validation calls or it can be a system warning. If the latter, it can either timeout or be updated each time a job type or recipe type is edited until all affected recipe types are cleared up and there are no more active recipe types with inactive nodes.

**Alternative / Workaround**
Currently there is no easy way to see a list of recipe types containing a job type or recipe type.

**Additional Context**

**Comment by emimaesmith** [comment]
Possibly add a field to the recipe type serializer to check if all jobs and sub-recipes are active. The UI would be able to use this field to add an indicator to the recipe type card to display if there is an issue with the recipe type that needs to be addressed (lists the number of inactive job/recipe types in the recipe-type list view card?). Similar indicator can be added to the job type in the recipe type view to visually indicate if the job type is inactive.

**Comment by JohnPTobe** [comment]
This relates to #1609

**Comment by JohnPTobe** [comment]
The recipe type details api essentially does this with the job_types and sub_recipe_types fields which have the is_active flag for each job/recipe type.  This isn't available when listing all recipe types and I think it would make that api too slow.  We need to decide if we want to return something from the edit method or just display a general warning that recipes may be deprecated along with the current job type or recipe type.

**Comment by JohnPTobe** [comment]
Also I think we should always deprecate recipes that contain a deprecated job/recipe regardless of the auto_update flag.  That flag should be reserved for simply updating the revision of jobs/recipes automatically.
