### ISSUE TITLE
Scheduler bug: too much sand for the couch.

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#172]
When the queue become very (very) full of small lightweight jobs it can starve larger jobs from finding a place to run.  Small jobs, even if at a lower priority, will "fill in" all the "holes" and then larger resourced jobs won't be able to run, so the scheduler will schedules more small jobs.  

The scheduler is maximizing utilization even at the cost of priorities.  The scheduler needs to be smart enough to know how to "look ahead" in order to "make a hole" for larger jobs if one is waiting.  --or (and this may be easier) be smart enough only to schedule 'small' fill-in jobs if (and only if) every node that _could_ run larger, higher priority jobs already was.  

We likened this to the problem that you couldn't move the couch into the living room becuase it was full of sand.  Even though some sand runs out, there's still no room for the couch... But there IS still room for more sand!

**Comment by tclarke** [comment]
Hmm...I'm not sure about any existing scheduling algorithms to explicitly address this. I'm initially thinking that we create an age ratio similar to HPRN such that the ratio goes up the longer a job has been queued. If any jobs have a ration above a threshold, jobs not in this class can at most accept a percentage of available offers (perhaps half). A similar option would be to randomly skip jobs and offers based on a random number adjusted for priority so jobs with a larger priority (less important) have an increasingly high chance of not running even if there is availability. Similarly, we could use a priority promotion strategy and at a certain point, jobs enter a "real-time" priority group. Anything in this group will prevent non-real-time jobs from being scheduled. Overall, these strategies would lower the efficiency and throughput but would prevent starvation of large jobs.

**Comment by cshamis** [comment]
The problem is that priority shouldn't be "trumped" for the sake of utilization.  

If all jobs are equal in priority, then it completely makes sense to maximize utilization and throughput.  So, it would be correct behavior to pack smaller jobs in... To a point... At some point we need to also look at LIFO vs FIFO weighting.  Certain recipes (or strike feeds) may prefer LIFO others might rather have FIFO... These are all huge headaches for a scheduler. 

The Linux block device drivers have several (schedulers) we could look at for ideas.  Fair queueing, deadline, anticipatory, naïve, and noop.  --Of course that's IO scheduling so it's a little bit different; but I'm sure we could always learn a few things by looking at them for inspiration.  

This is a fun computer science type problem.  

-C.

**Comment by dfaller** [comment]
This has been completed.
