### ISSUE TITLE
Timeout Ignored

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/scale#1728]
**Description**
I created a job type that sleeps for x seconds with a timeout of 60.  If I set the number of seconds to 61 it isn't timed out. I need to do more testing but it seems Scale ignores timeouts currently.

**Reproduction Steps**
Steps to reproduce the problem:
1. Create Job Type with a timeout value
2. Schedule a job of that type that takes longer than the timeout value
3. Job completes successfully

**Expected behavior**
Scale should terminate the job and fail it with an error.

**Screenshots**
N/A

**Version and Environment Details**
N/A

**Additional context**

**Comment by cshamis** [comment]
Does it eventually timeout?  There can be considerable lag in the system

**Comment by JohnPTobe** [comment]
Maybe; I looked into this after seeing a job run for a day in production a few weeks back. It needs more testing.

**Comment by cshamis** [comment]
Running for a day(s) can also occur if scheduler gets restarted while a job is still running.  The job eventually finishes or dies, but scale never checks back to "garbage collect."  

I think I put in a ticket that we should automatically fail any (prior) running jobs when Scale is initialized.  

Unless Scale can reattach to old jobs, but I don't think it can.

**Comment by JohnPTobe** [comment]
Ok, just tested with a timeout of 60 seconds and sleep of 300 and it failed within 2 minutes. Closing issue.

**Comment by cshamis** [comment]
Try it with one hour just for kicks.
