### ISSUE TITLE
Strike doesn't properly reload configurations

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1736]
**Description**
If a workspace is changed (i.e. change location it points to), the strike doesn't start watching the new location.

**Reproduction Steps**
Steps to reproduce the problem:
1. Create two workspace folders (input-1, input-2) and create a single workspace pointing to input-1.
2. Create a strike pointing to the workspace.
3. Drop a file into input-1 and watch the ingest kick off.
4. While the strike is running, update the workspace to point to folder input-2.
5. Drop a file into input-2 - no ingest will be kicked off for this file.
6. Drop a different file into input-1 without changing the workspace. Watch an ingest be kicked off for this file.

**Expected behavior**
When the strike reloads its configuration from the database it will pick up the new workspace location.

**Version and Environment Details**
 - Scale API: 7.0.0
 - Scale UI: 0.5.3

**Comment by emimaesmith** [comment]
The ingest job created from the strike with the second file is added to the original input will use the updated workspace location.

**Comment by Fizz11** [comment]
Fixed in #1814
