### ISSUE TITLE
Can't Cancel Scan

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1741]
**Pain Point? Please describe.**
Scans are currently unable to be cancelled. 

**Desired Solution**
A way to cancel the scan: the scan job and all ingests currently running/future scheduled.

**Alternative / Workaround**
Manually cancel ingests associated with the scan.

**Comment by JohnPTobe** [comment]
Get the event/ingest event for the scan and cancel all jobs with that event?

**Comment by emimaesmith** [comment]
closed via #1823
