### ISSUE TITLE
Transfer_suffix is required for directory strikes

### ISSUE THREAD

**Issue by Fizz11** [ngageoint/scale#1768]
**Description**
Transfer_suffix is currently optional in the UI, however the strike will fail if it is missing. 

**Reproduction Steps**
Steps to reproduce the problem:
1. make a directory strike

**Additional context**
easy fix is to set default value to _tmp if value is not provided in the UI. also update documentation to label it optional.

**Comment by emimaesmith** [comment]
Closed via #1771
