### ISSUE TITLE
Provide better return indicating stale scheduler

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1770]
This should not return a `204`.  Instead it should return something more indicative of the scheduler being stale.  

**Version and Environment Details**
 - Scale API: 7.0.1rc4
   - Can be found at `/api/v6/scheduler/status`
 - Scale UI: `0.8.4`
Cluster details below are very helpful for problem resolution, but external Scale users aren't expected to provide.
 - DC/OS: kraken

**Additional context**
https://github.com/ngageoint/scale/blob/330b6e6d15501faf52e069cf2a7f68619d959077/scale/scheduler/views.py#L145-L146

**Comment by JohnPTobe** [comment]
Return the status but with a field warning that it's stale?  Return only the stale warning with no status?  I assume the problem was you tore your hair out debugging the scheduler only to figure out it was slow so something more obvious would be nice.

**Comment by cshamis** [comment]
That bug was also complicated by some sort of hang up in the node deprecate code that confused the scheduler.
