### ISSUE TITLE
Input metadata manifest json

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#1775]
Does not formulate the permalink URL from the workspace url prefix.  Just gives the user the workspace ID.  

So, that kinda stinks.

**Comment by JohnPTobe** [comment]
I added some code to test this and from what I can tell this shouldn't have been working at all because of a bug in determining if the seed manifest has INPUT_METADATA_MANIFEST as an input.

**Comment by JohnPTobe** [comment]
After fixing that bug, here is what I get for the json:
`

{
	"JOB": {
		"input_2": [{
			"id": 1,
			"file_name": "my_test_file.txt",
			"workspace": {
				"id": 22,
				"name": "test-workspace-22"
			},
			"data_type_tags": [],
			"media_type": "text/plain",
			"file_type": "SOURCE",
			"file_size": 100,
			"file_path": "path/1/file1.txt",
			"is_deleted": false,
			"url": "http://test.com/path/1/file1.txt",
			"created": "2019-09-06T14:46:24.891612Z",
			"deleted": null,
			"data_started": null,
			"data_ended": null,
			"source_started": null,
			"source_ended": null,
			"source_sensor_class": null,
			"source_sensor": null,
			"source_collection": null,
			"source_task": null,
			"last_modified": "2019-09-06T14:46:24.891636Z",
			"geometry": null,
			"center_point": null,
			"countries": [],
			"job_type": null,
			"job": null,
			"job_exe": null,
			"job_output": null,
			"recipe_type": null,
			"recipe": null,
			"recipe_node": null,
			"batch": null,
			"is_superseded": false,
			"superseded": null,
			"meta_data": {}
		}],
		"input_3": [{
			"id": 2,
			"file_name": "my_test_file.txt",
			"workspace": {
				"id": 22,
				"name": "test-workspace-22"
			},
			"data_type_tags": [],
			"media_type": "text/plain",
			"file_type": "SOURCE",
			"file_size": 100,
			"file_path": "path/2/file2.txt",
			"is_deleted": false,
			"url": "http://test.com/path/2/file2.txt",
			"created": "2019-09-06T14:46:24.901146Z",
			"deleted": null,
			"data_started": null,
			"data_ended": null,
			"source_started": null,
			"source_ended": null,
			"source_sensor_class": null,
			"source_sensor": null,
			"source_collection": null,
			"source_task": null,
			"last_modified": "2019-09-06T14:46:24.901175Z",
			"geometry": null,
			"center_point": null,
			"countries": [],
			"job_type": null,
			"job": null,
			"job_exe": null,
			"job_output": null,
			"recipe_type": null,
			"recipe": null,
			"recipe_node": null,
			"batch": null,
			"is_superseded": false,
			"superseded": null,
			"meta_data": {}
		}, {
			"id": 3,
			"file_name": "my_test_file.txt",
			"workspace": {
				"id": 22,
				"name": "test-workspace-22"
			},
			"data_type_tags": [],
			"media_type": "text/plain",
			"file_type": "SOURCE",
			"file_size": 100,
			"file_path": "path/3/file3.txt",
			"is_deleted": false,
			"url": "http://test.com/path/3/file3.txt",
			"created": "2019-09-06T14:46:24.903349Z",
			"deleted": null,
			"data_started": null,
			"data_ended": null,
			"source_started": null,
			"source_ended": null,
			"source_sensor_class": null,
			"source_sensor": null,
			"source_collection": null,
			"source_task": null,
			"last_modified": "2019-09-06T14:46:24.903372Z",
			"geometry": null,
			"center_point": null,
			"countries": [],
			"job_type": null,
			"job": null,
			"job_exe": null,
			"job_output": null,
			"recipe_type": null,
			"recipe": null,
			"recipe_node": null,
			"batch": null,
			"is_superseded": false,
			"superseded": null,
			"meta_data": {}
		}],
		"input_1": "my_val"
	}
}

`

**Comment by cshamis** [comment]
Great!  Get it to Clint ASAP so he can begin writing new publishers for ndaas.
