### ISSUE TITLE
Investigate New Scheduler Architecture

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#179]
Investigate a new architecture for handling the scheduler and the nodes in regards to the PostGIS database. For long term scalability we need a way to move any database querying outside of the Mesos scheduler callbacks and to figure out how nodes should get data to and from the database.

One possibility to look into is a message passing architecture.

Make sure to remove the additional database query in queue/models.py at line 406.

**Comment by gisjedi** [comment]
Issues being tracked for this effort at https://github.com/ngageoint/scale/projects/6
