### ISSUE TITLE
Job Type Update of manifest impossible

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#1820]
**Description**
In Scale 5.x series, it is impossible to update the manifest from the API. This means any call to PATCH /api/v6/job-types/{name}/{version} will fail with InvalidJobField exception, if `manifest` key is included. This makes updates of an existing Seed job type impossible for patch versions.

**Reproduction Steps**
Steps to reproduce the problem:
1. Create a Seed Job Type via the API: POST /api/v6/job-types/
2. Attempt to update by patching with a minimal payload: PATCH /api/v6/job-types/my-job/1.0.0/
```
{ "manifest": ... }
```
3. Receive a 500 Server Error response.
4. See the InvalidJobField exception raised in the webserver logs.

**Expected behavior**
I'd expect it to work.

**Version and Environment Details**
 - Scale API: 5.9.7 (note the API in 5.9.7 lies and says its 5.9.6)

**Comment by gisjedi** [comment]
https://github.com/ngageoint/scale/blob/7.0.1/scale/job/views.py#L372 - 377 should be applied to https://github.com/ngageoint/scale/blob/5.9.7/scale/job/views.py#L699 - 703

**Comment by cshamis** [comment]
Won’t fix.  Move to 7.

**Comment by emimaesmith** [comment]
Closing as won't fix
