### ISSUE TITLE
Jobs View- Sort by Recipe not working properly

### ISSUE THREAD

**Issue by SaraDarrah** [ngageoint/scale#1821]
Under Jobs View- click on Sort by recipe (header column).  The descending isn't working properly...there was a p after a c (in descending setting).

**Comment by mheppner** [comment]
Sorting is done via the Jobs filter, which in this case, is filtering on a ForeignKey to recipe. I think the default sort order is used for foreign keys, but the Meta class for Recipe does not have a default order specified.
