### ISSUE TITLE
/files API slow to respond with a large database

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1831]
Calls to the v6/files API are timing out with a large dataset. The problem seems to be with the way we are querying data. The `filter_files` method needs be optimized to not select all files initially then filter down.

*Steps to Reproduce*
1. Navigate to a job details page and open the network tab.
2. Note the Outputs panel constantly loading and the request for the outputs timing out.

**Comment by emimaesmith** [comment]
Added timing to each stage of the response. It appears the majority of the time is spent during the serialization/pagination of the queryset rather than the actual database call.

```
[storage.models(404)] Time to fetch initial files: 0.000 seconds
[storage.models(545)] Time to order by last_modified: 0.000 seconds
[storage.views(117)] Time to get matching files: 0.001 seconds
[storage.views(123)] Time to serialize/paginate data: 0.466 seconds
[storage.views(126)] Time to finish files request: 0.467 seconds
```

**Comment by mheppner** [comment]
I'm not sure if I agree with Raul here. `filter_files()` doesn't select everything then filter down in Python, it's starting out with `.objects.all()`, yes, but all of the subsequent `.filter()`s are using the QuerySet object. The query isn't actually executed on the database until it goes to the views and `self.paginate_queryset(files)` is called.

I've optimized this by moving `'job_id'` from `.select_related()` to `.prefetch_related()`. Some timing metrics:
- page size 20: 54 queries at 3279ms (4.9s for request) -> 7 queries at 781ms (2.0s request)
- page size 1000: 506 queries at 28574ms (40.8s for request) -> 7 queries at 1420ms (9.1s request)
