### ISSUE TITLE
New page for job type error metrics

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#184]
Create a new page to display job type error metrics. You should be able to use the metrics API to get back the required data.

**Comment by ericsvendsen-mil** [comment]
Reopening the issue since it's not yet resolved.  Still working to add failure rates, total job counts, changing time window, and ordering the grid by highest failure percentage descending.

**Comment by ericsvendsen-mil** [comment]
Adding comments from @wardcr here for posterity:

* Having color on every single value I think will make it a bit hard to recognize important trends. I think we should consider some sort of scheme that introduces more variation. For example, only color the values with the highest count within a table cell or turn it into more of a progress bar where the width of the color is proportional to the % of the errors.
* Add a tool-tip over each value that shows the value as a % and the error category label.
