### ISSUE TITLE
Better alphabetical sorting

### ISSUE THREAD

**Issue by mheppner** [ngageoint/scale#1866]
**Pain Point? Please describe.**
See ngageoint/scale-ui#301.

API endpoints returning data sorted alphabetically are using default SQL sorting, which sorts case-sensitive. This can be seen on recipe types page, for example. Add multiple recipe types with lower and upper cases, and you'll see the capitalized ones are alphabetical at the top, followed by lower-case ones at the bottom.

**Desired Solution**
Case-insensitive sorting for REST endpoints.

This can be done by adding an extra `LOWER()` field to the query and sorting on that: https://stackoverflow.com/a/34506461

This looks like a good solution for DRF: https://stackoverflow.com/a/47347807

**Alternative / Workaround**
I can sort in some parts of the UI, but anything that returns paged results will obviously not be doable on the frontend.

**Comment by emimaesmith** [comment]
The UI sorts by the following columns:

**Jobs:**
- job_type
- recipe
- input
- created
- last_modified
- node
- status
- error.category
- error.title

**Recipe:**
- recipe_type.name
- created
- last_modified
- completed

**Batches:**
- title
- recipe_type
- is_creation_done
- jobs_total
- created
- last_modified
- Ingest records:
- file_name
- file_size
- strike.id
- status
- transfer_started
- transfer_ended
- ingest_started
- ingest_ended

**Scans:**
- name
- file_count
- job
- created
- last_modified
