### ISSUE TITLE
Message Handlers Are Not Properly Shut Down on Scheduler Restart

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1879]
**Description**
When shutting down the scale scheduler task, it would appear the message handlers do not shut down properly in a way to allow the new instance, when restarted, to start picking up messages again. The new service will appear to start a message handler task (or tasks - depending on how many handlers were set in the scheduler), but that task will not actually process any messages; this is evident in the handler logs, as well as the fact that no jobs - including Scale Clock - are started after the initial docker pull and cleanup jobs are ran. 

**Reproduction Steps**
Steps to reproduce the problem:
1. Shut down the current scheduler and wait for every task to completed.
2. Scale the scheduler to 1 instance.
3. Watch the service tasks start coming in and notice that only the scale.instance and message handler tasks are started.
4. Update the scheduler to +1 message handlers
5. Watch the scheduler service tasks start running again and the new message handler task is the only one to be processing messages.

**Expected behavior**
All tasks are properly shut down on a scheduler shutdown, then are able to be properly restarted when scaled back up.

**Comment by cshamis** [comment]
More important, can you trap and recover if they are not shut down clean?  

Should be able to pickup from any state.

**Comment by Fizz11** [comment]
Issue appears to have stemmed from mesos and DCOS were having sync issues, causing scale to use message handler instances not appearing in DC/OS. Closing for now unless it pops up again under different circumstances.
