### ISSUE TITLE
Verify all APIs allow v7

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/scale#1884]
All API requests should work with either v6 or v7. The queue new recipe (POST to /recipes) does not work with v7. In addition to fixing this particular request, we need to verify all API calls are checking the correct version numbers in the requests.

**Comment by Fizz11** [comment]
1. scale/recipe/views.py line 465 needs to be modified to allow v7
2. search code for other instances of this check, and verify we don't have this bug elsewhere. 
3. build and deploy to test cluster and verify all changes.

**Comment by emimaesmith** [comment]
closed via #1904
