### ISSUE TITLE
Refactor Scale walkthrough to eliminate use of `ENTRYPOINT` 

### ISSUE THREAD

**Issue by mattbanderson** [ngageoint/scale#1890]
**Pain Point? Please describe.**
The example in the [Scale walkthrough](https://ngageoint.github.io/scale/walkthrough/output/index.html) uses an `ENTRYPOINT` script. This somewhat obfuscates the full command that is being run and is a pattern we would like to avoid in our example documentation.

**Desired Solution**
Update the example in the Scale walkthrough to more closely match the Seed user guide example, which does not use `ENTRYPOINT`: https://ngageoint.github.io/seed-cli/#_sample_algorithm

**Alternative / Workaround**
The example works as-is, but this will align our examples to be more consistent across documents.

**Comment by cshamis** [comment]
This can be confusing.  Entrypoint and CMD[] are
sooooo easy to confuse, ESPECIALLY when you’re passing Argument to an interpreter. 

Take time to make sure it’s being explained VERY carefully.

**Comment by mattbanderson** [comment]
The pattern we are following is to use neither `CMD` nor `ENTRYPOINT` in the Dockerfile. As a result, the Seed CLI user must specify the full command with arguments in the Seed manifest. We felt this makes it more clear to the Seed user the full command that is being executed, rather than it being split between the Dockerfile (command) and Seed manifest (arguments).
