### ISSUE TITLE
Refactor ingest system

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#19]
Refactor the ingest system to remove NFS requirement.
Implement new monitor system to allow Strike to have different ways of receiving ingest file events

**Comment by dyerz** [comment]
One note for when refactoring the ingest system. Currently, if you retry a failed ingest that has some of the file-related database records, the ingest will be marked as a duplicate and that the job will exit as a success.

**Comment by dfaller** [comment]
For this issue we will need to consider how the long-running Strike process can detect issues with a Docker NFS mount and exit so that a new container (job execution) can be started.

**Comment by dfaller** [comment]
Also don't forget to remove the ENABLE_NFS env var being passed to the ingest and Strike containers.

**Comment by dfaller** [comment]
Here are a few notes that I had scribbled for this issue as a potential design:

Add read_only flag to workspace, should throw exception when changing things in workspace

Strike config:

	monitor:
		workspace (has a broker config)
		monitor config (watch directory within NFS, S3 events)

	what to do:
		filename regexs -> data types, workspace, new workspace path

monitor takes monitor config in constructor
monitor has methods for:
	is the given workspace broker type valid for this monitor?
	given a workspace, perform the monitoring (blocking call), also needs to be given some class for call backs to create/update ingest records and create ingest tasks
	method to kill/stop monitoring

event of file arriving has the following things:
path of file in Strike workspace
basic info of file (file size, media type)

how to ingest the file has the following things:
basic info of file (data types), this is new stuff based on Strike config
new workspace
new workspace path

ingest job steps:
	if strike workspace and final workspace are same, just do a workspace move (if new workspace path is provided)
	if workspaces different, do a type lookup on Strike and final workspace to find class that does optimal transfers
	if no special optimal transfer, just do a straight download to local disk from Strike workspace and upload to final workspace

rethink ingest statuses?

**Comment by dfaller** [comment]
Example new Strike configuration schema:

``
{
  "version": "2.0",
  "workspace": "my-workspace",
  "monitor": {"type": "s3", "sqs_name": "my-sqs"},
  "files_to_ingest": [
    {"filename_regex": ".*", "data_types": [], "new_workspace": "my-workspace", "new_workspace_path", "my/path"}
  ]
}
``

**Comment by ericsvendsen-mil** [comment]
@dfaller Am I correct in guessing that there should there be a colon after `"new_file_path"` instead of a comma?

**Comment by dfaller** [comment]
Yeah, it's corrected now. :)

**Comment by dfaller** [comment]
Key Change Log Notes:
- new automated workspace which requires host mounts of NFS
-  in DB migrations note that failed ingest jobs cannot re-run successfully, must cancel and ingest the file again
