### ISSUE TITLE
Instability with 5.9 and DC/OS

### ISSUE THREAD

**Issue by Fizz11** [ngageoint/scale#1900]
**Description**
When a Mesos master leader election event occurs it commonly results in the presently running Scale framework being stuck in an inactive status while a new one comes online. This results in 2 schedulers running and executing workloads. One "ghost" scheduler that is under the Mesos `inactive frameworks` and another one that is under Mesos `active frameworks`. The end result is you get the same jobs running twice causing sequence id collisions and general mayhem.

**Reproduction Steps**
_Note:_ Since this happens on an infrequent basis (every few weeks in some operational environments) these are a best case on reproduction steps.
1. Multi-master deployment of Mesos (3,5)
2. Scale framework registered and accepting tasks as an `Active Framework`
3. Restart the leading master and observe leader election event has occurred.
4. Observe that Scale is left with an inactive Mesos framework running and is restarted as a new active framework.

**Expected behavior**
Scale should handle the leader election event in one of two ways. 

1. Framework is properly shutdown and marked as completed during a Mesos leader election event. All tasks running under framework are stopped.
2. Framework is interrupted but then access is properly restored to same framework id following Mesos leader election event. All tasks running under framework continue and Mesos status events are recognized and acknowledged following scheduler restoration.

My preference would be for 2, but 1 is the status quo and so that is probably a better scope for this issue.

**Version and Environment Details**
 - Scale: 5.9.7
Cluster details below are very helpful for problem resolution, but external Scale users aren't expected to provide.
 - DC/OS: 1.10.11
 - Marathonlb: [e.g. 1.4.2]
 - Agent OS: CentOS 7 Kernel 3.10.0-957.1.3.el7.x86_64

**Comment by cshamis** [comment]
Bummer but unless it’s a configbchange or a health check that can fix it we’re done with 5.9.

**Comment by gisjedi** [comment]
This problem is present in 7.x series as well, so I'd propose we isolate the problem and backport it as a patch release for 5.9.x.
