### ISSUE TITLE
DR: NFS is easily overwhelmed by large clusters with many jobs with many mounts

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#196]
When there are a great many nodes running many jobs, each with a live connection to a NFS workspace the NFS server can become overwhelmed and start timing out or hanging.  Increasing the number of NFS daemons helps, but is not sustainable.  Other, more scalable, approaches will be necessary in the future.  Off the top of my head, these options may include (but are not limited to) Lustre, HDFS, pNFS, WebDAV, S3, and Ceph.  Hybrid solutions involving FTP, SCP, HTTP, BBCP, Docker DataContainers, or a just a more "restrained" use of NFS may be required.

I would like to start the discussion on finding a suitable replacement for our heavy reliance of NFS, and so we can have an implementation plan ready by the start of next sprint.

**Comment by dfaller** [comment]
This is OBE.
