### ISSUE TITLE
Add config for strike for "replace duplicates" default behaviour

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#197]
Presently, if strike encounters a duplicate file, it marks as duplicate and sets the file aside.  This is right and correct for most of our workflows.  However, we may have a situation where we would want the old file marked as "deleted" in the db, and then new file "re-ingested" and re-processed automatically.

A config option on strike on how to handle duplicates, (set aside | throw away | mark as deleted and re-ingest and reprocess) would be useful in certain situations.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
