### ISSUE TITLE
Add product output directories

### ISSUE THREAD

**Issue by wardcr** [ngageoint/scale#201]
Currently if a job generates a large number of files, such as a tile pyramid of PNG files, each individual file is recorded in the database. It would be better in cases like this to only record the existence of the top-level directory and associated meta data needed to access the tiles, rather than every file.

**Comment by cshamis** [comment]
Couldn't you bypass this by changing the recipe by zipping before storing?  

Especially If files aren't to be used downstream jobs?

If goal is to publish to an external file system (like pyramid tiles) then could  have a new job unzip tiles somewhere.  This is the pattern  we use for database loaders.

Although that would mean storing the zip and the tiles... of course could just write tiles to final dest, and then just NOT register them in the output manifest... hmm

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
