### ISSUE TITLE
Jobs Occasionally Stuck Running

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#205]
I've found that occasionally jobs will get stuck in the running state even though the job has completed.

In some cases, the job is still in the running state in mesos, but in other cases, the job has been removed from mesos.
Either way, the job stays in the running state according to Scale until the timeout is triggered. 

When the timeout happens, the job is removed from mesos (if it was still in mesos), and it is marked failed.

There have been cases when this happens and the job is still in the ####_job stage and cases when this happens and the job is in the ####_post stage.

When the job is ended this way, the correct error code, if any, is not applied to the job.

**Comment by dfaller** [comment]
What version of Mesos are you running?

**Comment by dyerz** [comment]
0.27.1

**Comment by dfaller** [comment]
We might want to have some periodic reconciliation check where we ask Mesos the status of the tasks Scale thinks are running more often than a job timeout.

**Comment by dfaller** [comment]
This was a bug in a forked copy of Scale. Closing.
