### ISSUE TITLE
Add a credential database to scale

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#208]
Add a way to securely register credentials with scale and allow their use without revealing the credential values. This would be used for algorithm database passwords, etc. This could be patterned after the jenkins credential registry.

**Comment by cshamis** [comment]
This could also be the mechanism for other job/recipe specific "parameters".  Could support passing static or dynamic tuples via JSON, cmdline args, or env variables.

**Comment by gisjedi** [comment]
Superseded by Vault secret implementation.
