### ISSUE TITLE
Upgrade to latest Mesos

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#21]
Update Scale to use the latest stable version of Mesos.

This should remove our need to do an explicit Docker pull in the pre-task. Test this!

Update the node.slave_id column to agent_id to reflect the new name in Mesos.

Check for updated Python bindings/stubs and see if we can remove the protobuf dependency.

**Comment by gisjedi** [comment]
Protobuf binding has been removed and newest version of Mesos is now supported using v1 Scheduler API. This was completed in #1383.
