### ISSUE TITLE
Node UI Feature Request

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#213]
It would be great to be able to navigate from the node status page to the list of jobs running on each node. Or to be able to show that information directly on the jobs table.

**Comment by dfaller** [comment]
We have a plan to show the currently running executions on the node detail page. Will this work or are you looking for something else?

**Comment by dyerz** [comment]
The more I use the UI, the more I would like to have last executed node name in the Jobs table, much like the addition of the error categories column in #181.

**Comment by dfaller** [comment]
Others have brought this up before. Let me get some buy-in from the stakeholders.

**Comment by dfaller** [comment]
The node is now returned in the jobs REST API. It will be added to the jobs table in the new Scale UI.
