### ISSUE TITLE
Security for local_settings_docker.py

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#220]
Make a couple of security updates for the local_settings_docker.py file.
1. Make sure that a warning is logged if/when the Scale web server (and Scheduler?) is started with the insecure default SECRET_KEY value. INSECURE_DEFAULT_KEY is defined in settings.py. I think using a default value is OK for the job containers since that value is only used by Django for web stuff, but verify this.
2. Figure out the best way to handle ALLOWED_HOSTS. The settings.py file uses a default of only localhost, while the local_settings_docker.py uses a default of *. Figure out something that is both secure and will work with Docker.

**Comment by gisjedi** [comment]
This has all been addressed in the deployment refactor prior to DCOS Universe release.
