### ISSUE TITLE
Host broker security

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#221]
Look into a couple things to improve security for the host broker:
1. Force the host broker to copy its input files into the input_data named Docker volume so that the host mount does not get mounted into the main job container. This possibly sacrifices some performance for security. We might want a broker field indicating whether a file system mount is required for the job container to improve other brokers as well.
2. Restrict some obvious "bad" paths (such as "/") from being accepted in the host broker validation. Bad paths also need to be restricted for host volumes defined in a JobConfiguration for mounts. Create a standalone utility that checks for bad paths.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
