### ISSUE TITLE
Build and Install Documentation

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#223]
Update the Sphinx docs to document how to do a Docker build of Scale and how to deploy/run Scale, both in DCOS and on bare Mesos. The current portion of the Sphinx docs talking about install and development are quite old. This should include a description of all of the environment variables that can be passed to the Scale Docker when you are starting the scheduler/web server and this description should be visible on Dockerhub.

**Comment by gisjedi** [comment]
Deferring work to #443
