### ISSUE TITLE
Fix input/output volume owner and permission issues

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#229]
Docker volumes for job input/output are perm 0755 owned by root so algorithm containers which execute as a non-root user will have permission issues. The owner of the volume should be the "standard" unprivileged users (uid 1001) or the top level permissions should be 0777.

**Comment by dfaller** [comment]
We've fixed the ownership so that the input and output directories are owned by Scale, but I think we want to also chmod the output_data to 0777 so the job task can write to it as any user.
