### ISSUE TITLE
Ingests API Feature Request

### ISSUE THREAD

**Issue by dyerz** [ngageoint/scale#251]
Could we add file_name as a query parameter to the /ingests/ API endpoint? Thanks.

**Comment by dfaller** [comment]
We have the source file detail now. You can submit a source file name and part of the response will contain the list of ingests for the given source file name.

http://ngageoint.github.io/scale/docs/rest/source_file.html

Is this sufficient for what you need, or would you still like to query ingests by file name\?

**Comment by dyerz** [comment]
That is helpful, but there have been some cases where ingested files failed before being assigned a source file id. So I would still like to be able to query ingests by file name.

Thanks

**Comment by dfaller** [comment]
Ah, we need to update the ingest job so that ingests get linked to the duplicate source files.

**Comment by dyerz** [comment]
In some cases though, the source file has not yet been created. The duplicate source files issue is a different issue we have observed.
