### ISSUE TITLE
Scheduler Initialization Task

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#253]
To significantly ease deployment, have the scheduler go into an initialization phase when it first starts up. During this phase, it has no database interaction and does not start any threads that perform database interaction. Upon receiving resources from Mesos, it schedules a Scale Initialization Task that performs the following steps:
1. Database migrate
2. Database load initial data
3. Create Scale Clock job and scheduler model if needed (current initialization)

After the initialization task has finished successfully, the scheduler goes into normal operation. This will simplify deployment into DCOS because DCOS will only need to kick off the long-running scheduler container and not mess with database setup tasks.

One concern is that after this, the Scale REST API/UI will break until the initialization task is finished. We need to figure out a good way to communicate to the web server when the scheduler is in the initialization phase and when the initialization phase is over.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
