### ISSUE TITLE
Add support for constants for input values in Recipe Types

### ISSUE THREAD

**Issue by dickmancj-mil** [ngageoint/scale#26]
In order to improve reusability of Job Types, Recipes should support specifying constants for values of Job Type inputs. 

Example: Job Type "Send E-mail" that has inputs "sender" and "recipient". Scale currently requires creating separate Job Types and Docker images for each unique configuration. The Recipe Type should support user defined values for these inputs.

**Comment by cshamis** [comment]
Chris:  Good thinking!  

I was talking to Derick this morning that having a way to attach a "parameter" object to a recipe (or job) like we assign a workspace would be very powerful.  For example: for strike ingests may use one "parameter" set whereas a experimental, background, add-hoc or reprocess could use a completely different "parameter" set.  In actuality might be as simple as a JSON with tuples.  Things we could put in might be database names and passwords for ingesters, or file locations for publish-type jobs, or maybe control options for processing type jobs... We should be careful to make sure that one job can't see another jobs parameters though. I.e. JOB A, shouldn't be able to see or know JOB B's database password for example... thats bad juju.  But there might be room for recipe-level globals that any job might be able to see.  We could build a "parameter" editor that goes with each recipe that let's you build up name, value pairs, then assign them as job-level, or recipe level... maybe even a switch to tell scale to make these environment variables inside the docker container, or supply on command line, or add the JSON as a file in the docker container...  assuming we can figure out how to do that in docker.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
