### ISSUE TITLE
Refactor Pre and Post Tasks

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#272]
Refactor the pre and post tasks:
1. Rename commands to scale_pre_task and scale_post_task
2. Move the pre and post logic into their own respective modules. The management command modules should only be concerned with the CLI. Factor out any business logic from the job_interface and job_data modules.
3. The saving of products and parse results in the post task should be in separate transactions so file system operations are not being done in a transaction. Save products first.
4. Pre tasks should check that all input files are present (independent of broker). If not, pre task should exit with a system error.
5. Update exit code handling so that pre and post tasks and all system jobs use the same exit code mapping. Create a base exception in the error app that represents a "Scale error exception". It will have both an exit code field and a Scale error name field. All errors that could be returned by any system tasks should have a corresponding derived exception that gets thrown. Then all system task/job code can have an overall try/except that catches the base exception and returns the correct exit code.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
