### ISSUE TITLE
Job Status Icons

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#275]
Add icons for the various job statuses. Display these icons everywhere that the job status is displayed (jobs table, job detail, recipe detail, etc).

Use the following icons to start (we can gather feedback after the initial cut):

PENDING  f017
BLOCKED f256
QUEUED  f0c9
RUNNING  f013
COMPLETED  f00c
FAILED  f00d
CANCELED  f05e

Here is an icon for when superseded jobs/recipes have been implemented:
SUPERSEDED f24d

Also use superseded icon in jobs table.

**Comment by cshamis** [comment]
Colors should be consistent everywhere as well.  Make this a top level item in the CSS where the icon and color are in one place so it will be easy to change universally.

Also, I'd like to suggest (where appropriate) that the status "throb" to indicate static (terminal) or dynamic states.  i.e.:

"Terminal" states.  
FAILED = RED
COMPLETED = GREEN
CANCELED = MAGENTA <= This should be very rare, so it should really REALLY stand out.
BLOCKED = BLACK
SUPERCEDED = GREY

"Dynamic" states: (icons, and even the css:label backgrounds) should throb slightly.
QUEUED = LAVENDER (slow) ~3 sec pulse between ~50% and 100% opaque lavender.
PENDING = PINK (little faster) ~2 sec pulse between ~50% to 100% opaque pink.
RUNNING = BLUE (slightly faster still) ~1 sec pulse ramping from ~10% to 100% opaque blue.

**Comment by wardcr** [comment]
I would suggest avoiding pink since it's sometimes associated with the red scheme of errors. I think you could represent pending/queued as varying shades of blue or purple to show the progression like this:
http://colorbrewer2.org/?type=sequential&scheme=Blues&n=3
or this:
http://colorbrewer2.org/?type=sequential&scheme=Purples&n=3

Alternatively, yellow is also a common choice for pending actions.

**Comment by cshamis** [comment]
True.  But, there's pale red pink, and then there's pink elephant pink.  

Pale red pink, yes.  I can see your point.  But pink elephant pink should be "pink" enough to not be confused.  

But we can try them all.  

If we also add unambiguous iconography then there shouldn't be any confusion. ---Even if we simply color-ramped 8 levels of greyscale.

-C.

**Comment by wardcr** [comment]
Okay, maybe you haven't seen it yet, but the job failed status error message is now displayed with a light pink background box at the top of the job details page and log page, which is what I was thinking of when I made that comment.
