### ISSUE TITLE
Django Auth Integration

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#280]
Integrate the REST API with the Django authentication system.

Require authentication for modification requests (PUT, POST, PATCH).

Need to decide if any GET requests need protection (sensitive data returned).

Track users for events that create jobs/recipes.

**Comment by gisjedi** [comment]
Do we want history on anything other than jobs / recipes presently? I was thinking possibly workspaces, strikes and scans, but I'm trying to limit the history tracking to the areas we really need it.

**Comment by gisjedi** [comment]
I've begun the process of GEOAxIS integration as they offer an OAuth provider. This will allow us to delegate authentication and user identification to an external service, greatly simplifying the authorization flow. It will be our responsibility to define a role administrative users will be added to.

**Comment by gisjedi** [comment]
The present plan for implementation is 3 phased:
- Define access control to be applied to all endpoints. All POST/PATCH endpoints will require admin level access, excepting `/*/validation/` endpoints. Need the ability to toggle between public and authenticated GET endpoints. This will allow us to control API access under more restrictive security postures.
- Apply token and session support to all endpoints, with Django admin user management. Superusers will be able to admin users, admins will be able to call all API endpoints.
- Add support for GEOAxIS integration. Superusers will still have to grant access to user's being provisioned from middleware.
