### ISSUE TITLE
Fix Exit Code Parsing

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#289]
In the newer versions of Mesos (both 0.25 and 0.24 in DevNet), Scale is no longer parsing exit codes from Mesos. This results in no exit code information for Scale and all errors end up being unknown.

Two possibilities for the bug are:
1. Using the incorrect version of the Mesos Python egg
2. Mesos updated their interface (we are parsing the exit code from the "message" string field of a Mesos TaskStatus, so it is fragile)

**Comment by tclarke** [comment]
Looks like the status message format has changed from "Command exited with status 42" to "Docker container run error: Container exited on error: exited with status 42"
Removing "Command" from the regexp should allow it to work with either format.
