### ISSUE TITLE
Ingest Records UI issues

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#298]
The default sort on Data Feed->Ingest Records should be newest to oldest.  

Number of rows displayed doesn't resize correctly.

**Comment by wardcr** [comment]
Also while you're updating the ingest table page, I noticed the table footer in the bottom right corner showing number number of items is overlapping the vertical scroll bar.

**Comment by ericsvendsen-mil** [comment]
@cshamis just to be clear, by newest to oldest are you referring to the ingest_started field?  Or one of the other date fields (e.g. transfer_started, created, or last_modified)?  See http://ngageoint.github.io/scale/docs/rest/ingest.html for reference if needed.

**Comment by cshamis** [comment]
Ingest started is fine.  The newest stuff coming in should always be on top.  (By default).  

-C.

**Comment by ericsvendsen-mil** [comment]
I think the best solution is moving the paging controls outside the grid entirely.  It seems the Angular UI Grid doesn't like to play nicely with a fixed-height.  Below is a screenshot of what I have so far.  Once the page count gets beyond 5, an ellipsis will appear between 5 and the last page number available (e.g. 1 2 3 4 5 ... 118).  I think the main thing we lose by using this particular control is the ability to jump to a specific page, but that's something we can add if necessary.  Thoughts?

![image](https://cloud.githubusercontent.com/assets/15909071/15725663/f245917a-281a-11e6-8192-df444a3b5adf.png)

**Comment by cshamis** [comment]
Erîk:

I think that looks fine.  If you add a simple search box that operates as substring on filename I think you have a winner.  

Like the Google rule... If what you want isn't on the first page, refine the search...

-C.

**Comment by wardcr** [comment]
I'm okay with having a separate, but more limited pager. I don't think jumping by a large number of specific pages is very useful vs. more filtering like Chris said. I'm not sure about placing it in the upper-right vs. the more common bottom footer position. Is there a reason to have a fixed height table vs. just using normal vertical scrolling behavior for a list of results?

**Comment by ericsvendsen-mil** [comment]
I thought it was a cleaner look having it up top, but I'm not opposed to moving it back underneath the grid.  I'll do that and add in the filename filter as well.

To answer your other question - no, there's no reason in particular that I can think of or remember.  I know John wanted Job Types and Recipe Types to not use normal vertical scrolling behavior and I think that just kind of trickled over into the Jobs and Recipes views as well.  That's kind of the story with the whole app in general.  I think we would be well served by taking a step back and evaluating our presentation of data and components throughout.

**Comment by cshamis** [comment]
Now your talking sense.  Doing what John says instead of doing what he wants always causes trouble... :-)

But srsly, the "types" as "categories" are at a different hierarchy than the list-type tabular data, so it makes some sense to treat them slightly different...  

-C.

**Comment by ericsvendsen-mil** [comment]
Here's the latest version.  Pagination controls are at the bottom, added a dropdown to select page size, and added a filter for the filename.

![image](https://cloud.githubusercontent.com/assets/15909071/15781987/84111cbc-2976-11e6-8605-50d026ff2c88.png)

**Comment by dickmancj-mil** [comment]
LGTM

**Comment by cshamis** [comment]
Does the filter apply to the "entire" date range?  Or just the viewable rows?  If just the viewable rows, it's kinda worthless... 

Should/could it be moved up on the same line as the dates?   Then it would unquestioningly be part of the "overall" search parameters..

IMHO.

-C.
