### ISSUE TITLE
Modify the main.yml file to fix Docker error

### ISSUE THREAD

**Issue by bacherbikes** [ngageoint/scale#30]
Docker does not load properly using YUM unless lvm2 is updated first.  Here is the fix.

file:
scale/ansible/roles/common/tasks/main.yml
...
- name: Install python-pip
  yum: name=python-pip
  become: true

- name: Update lvm2
  yum: name=lvm2 state=latest
  become: true

- name: Install docker-py
  pip: name=docker-py
  become: true

- name: Install docker
  yum: name=docker
  become: true
...

**Comment by bacherbikes** [comment]
Bug from Redhat.
https://bugzilla.redhat.com/show_bug.cgi?id=1294128

**Comment by tclarke** [comment]
This has been fixed in 6304b1eb3f48129418f6a049c723d455784d9b3f
