### ISSUE TITLE
Fix the hard coding for the machine.vm.synced_folder in the Vagrant file

### ISSUE THREAD

**Issue by bacherbikes** [ngageoint/scale#31]
Fix the hard coding for the machine.vm.synced_folder in the Vagrant file.  Using the "~" will prevent the user from needing to create the hard coded path specified in the file.  Modify the vagrant quick start documentation to reflect that the synced folder may need to be modified if the project is not installed at the user's home directory.
file:
scale/vagrant
....
machine.vm.synced_folder "~/scale/", "/scale/"
...

**Comment by tclarke** [comment]
Current configuration uses a git repo clone and links the repo root to /scale. If the vagrant folder is moved out of a repo, this would need to be changed but it not a supported setup for the quickstart.
