### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale#310]
Add Gulp task to append a datetime stamp (or some other identifier) to the css and js reference links so whenever a new build of the UI is deployed it will force a fresh download of static resources by the client.

**Comment by wardcr** [comment]
I suggest using a hash of the file contents as the identifier and then also adding some sort of convention such as ".cache" to the file names that are processed. For example: my_scripts.js -> my_scripts.1234567890.cache.js
That way, we can also configure the cache headers on the web server to tell the clients they can safely cache that file forever, which avoids making even the HTTP 304 requests for optimal page load performance.
