### ISSUE TITLE
Job standard for algorithm publish and discovery

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/scale#324]
There is a need to define a reduced subset of the JobType interface to store as an algorithm manifest when publishing. The current plan is to store this alongside the algorithm Docker image as a LABEL in the Dockerfile. The JSON manifest will be serialized into a pre-determined LABEL for discovery by Scale.

We've been tasked with creating this as a standard interface not explicitly tied to Scale.

This issue must be completed in order to define the output that will be created in the CLI issue for algorithm publish: https://github.com/ngageoint/scale/issues/224

**Comment by icy-gisjedi** [comment]
WIP document tracking proposed changes to JobType JSON to support standard format.

[JobTypesStandardization.docx](https://github.com/ngageoint/scale/files/301400/JobTypesStandardization.docx)

**Comment by icy-gisjedi** [comment]
I'm doing all work here presently: https://github.com/gisjedi/jobpack I'm under the impression that John will want us to host this in some sort of standalone url once complete.

**Comment by icy-gisjedi** [comment]
For those that don't have the interest or time or software to pull down and review the change tracked Word doc, here is a distillation of the changes under discussion for the published manifest from the existing JobTypes format:

- Remove all priority, scheduling and docker specific keys from standard. This includes the _docker_privileged_, _docker_image_, _priority_, _max_scheduled_, _max_tries_ keys. This has no effect on the Scale implementation of Job Type, as these would be generated or derived on job discovery.
- Elimination of all version keys except algorithm version in favor of versioning as a whole by standard version. This includes _error_mapping.version_ and _interface.version_. This will likely have an impact on Scale as schema validation will now be handled for the entire Job Type object as a single version rather than individually for interface and error_mapping objects.
- Define error code mappings on a per Job basis instead of system-wide. This will eliminate potential name collision between Job Types, but still allow error analysis cross Job version upgrades. We need a good estimate on what parts of the system are impacted. Derick's initial feedback was that this would affect the REST APIs (import/export), underlying models and error capture code.
- Finally, the most problematic is my desire to eliminate the the results manifest. My suggestion was to provide a new glob pattern kvp in the _interface.output_data_ section for capturing in place of expliciting mapping _output_data.name_ keys to file names in the result manifest. I felt this greatly simplified the requirements on the standard, but with the need for Scale to receive spatiotemporal metadata about files or arbitrary string values, there may be no dodging this complexity.

**Comment by icy-gisjedi** [comment]
Also, what are we going to call this standard? I think my preferred name is JobPack, both for brevity and descriptiveness. Derick liked something that was more indicative of these being algorithm containers. I can't think of a good name for that though. Suggestions?

**Comment by tclarke** [comment]
Another thing that needs to be addressed is how will this be indicated as a standard? I'd suggest publishing as an Internet RFC since this deals with discovery and indexing on WANs.

**Comment by tclarke** [comment]
Do we really need a separate label for the version? If there are two labels we need to deal with what happens when one is present and not the other. Since we're defining the primary label as json there's no reason we can't have an inline version key.

**Comment by tclarke** [comment]
I'd suggest instead of requiring specific naming on the hub we ask the docker team to add label search capability. In the interim, have users register specific users/groups and we just pull images from those users and groups to search for labels.

**Comment by tclarke** [comment]
Needs to be better explanation of the specifics of the fields for a standard (the devil is in the details). Such as, what does the disk space multiplier mean? Does it multiple the size of all input files? What about data not in files? If it's only one file, how do you specify which file?

**Comment by icy-gisjedi** [comment]
@tclarke Thanks for the feedback. My response to your comments are given in the order of your replies.

> I'd suggest publishing as an Internet RFC since this deals with discovery and indexing on WANs.

I think the standard route via RFC is a good target. I'm not sure that we have the adoption or external interest yet to get traction there yet. I like the GeoJSON standard track - gain ubiquity as a simple de-facto standard and then pursue RFC.

> Do we really need a separate label for the version?

I agree with you that there is really not a huge value in 2 labels. That could just be validated on manifest evaluation. We could just include that as a top level key in the manifest JSON.  Something like:

``` 
{
"manifestVersion": 1,
"jobs": [...]
}
```

Do you have a preference on semver vs a simple sequence number on breaking changes? My preference is semver.

> I'd suggest instead of requiring specific naming on the hub we ask the docker team to add label search capability.

We are absolutely pursuing this route for the DTR, as well as investigating what it would take to add search for Docker Hub and the open-source Docker Registry. I've got requests in with Docker sales reps and through the government channels to push for a Label search capability we got added to the backlog in a future DTR release. My intention is to document the current means in place to discover based on a name suffix, with a future deprecation plan for pure Label search.

> Needs to be better explanation of the specifics of the fields for a standard (the devil is in the details).

100% agree, just haven't accomplished that yet. Now that we've mostly agreed upon what goes in to the manifest I'm going to address the types, ranges and units of all fields, as well as provide a JSON schema for the entire manifest.

**Comment by tclarke** [comment]
Answers work for me.

**Comment by icy-gisjedi** [comment]
Draft up and ready for review at https://gisjedi.github.io/jobpack/.

We need to settle on a standard name and where to host. The name should capture the concept of discrete work units packaged in a isolated container.

Please +1 with your preferred choice or contribution. Names under consideration:
JobPack Standard
Work Encapsulation Standard (WES) - JP4 credit

**Comment by icy-gisjedi** [comment]
This can be called "done". The repo and compiled documentation are now residing at https://github.com/ngageoint/seed/. If you have comments or updates, please make them there. The scale-caliper team owns that repo as well, so everyone should have full access.
