### ISSUE TITLE
Pausing Nodes

### ISSUE THREAD

**Issue by dickmanp** [ngageoint/scale#331]
I no longer seem to have the ability to pause a node in the UI when logged in as admin.

**Comment by ericsvendsen-mil** [comment]
Does logging out/in make a difference? `/#/admin/logout` and then `/#/admin/login`  Also, make sure you're zoomed in enough on the nodes to see the pause button.

**Comment by dickmanp** [comment]
Logging out/in does not seem to matter.  I see all of the other things I would expect as an admin.  I'm not sure what you mean by being zoomed in enough.  I just go to the nodes page.

**Comment by ericsvendsen-mil** [comment]
Yeah, use the scroll wheel to zoom in/out when the cursor is over the node grid.  This got changed a month ago or so to accommodate the 200 nodes in the static demo.  This, along with the jobs grid on the overview page, needs to be revisited though.  But for now the node pause icon is hidden unless you're zoomed in.

**Comment by dickmanp** [comment]
After zooming in for quite a bit, I was able to make the pause icon appear.  However, I'm not sure how a user would know to do that.  I didn't even know zooming was possible.

**Comment by wardcr** [comment]
It might be better to have some sort of fixed header or details panel that would show the pause button among other things when a node is selected instead of doing it on the node itself after zooming.

**Comment by dfaller** [comment]
Merged into master
