### ISSUE TITLE
Investigate Scale Changing Source File Extension

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#332]
A customer has reported the following:

> I copied a file with extension = “FOO.NTF”, but it stores it as “FOO.ntf”. When I queried for the status, I passed /sources/?file_name=FOO.NTF, but this wasn’t found. I queried /sources/?file_name=FOO.ntf and it was found.

Investigate what is causing the file extension to be made lower case and see if the behavior can be changed. Also consider if there is any reason why this behavior would be desired.

Also investigate if this issue affects product saving as well.

**Comment by cshamis** [comment]
S3?  Something getting sanitized through by a parameterizer?
