### ISSUE TITLE
Write integration / stress test suite

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/scale#337]
We need a means to test the complete Scale application with a reasonable data load in order to validate API usage and performance representative of a production installation.

Integration testing needs: 
- CloudFormation template for all supporting resources (EC2/S3/RDS/VPC/roles)
- Install DCOS Universe packages (Scale, marathon-lb, chronos)
- Create workspace for S3 and NFS
- Create job type to perform some basic work (hash of input file)

Stress testing needs:
- Install DCOS Universe packages (chronos)
- Use Chronos to place the same file into ingest directory every X seconds (mod file name with timestamp to avoid reprocess).
- Evaluate API performance over time as job history grows.

**Comment by gisjedi** [comment]
Focus first on on-prem based testing to pre-allocated AWS resources (S3/SQS). This will allow us to perform deployment/integration testing of all Scale components without being required to automate provisioning AWS resources through a privileged API user.

### Basic deployment pre-reqs
- DCOS running with 1 public and 3+ private nodes
- S3 bucket -> ObjectCreated notifications wired to SNS -> SQS

### Deployment steps
- Wipe DCOS cluster by removing ALL Marathon apps (maybe use Zookeeper flush of Marathon)
- Remove all mounts from nodes
- Mount NFS and S3 bucket to all nodes
- Elasticsearch DCOS package deployed, wait for healthy

### Integration testing needs
- Logging testing to ensure complete and ordered logging
  - This could consist of custom job writing out varying volumes of logs with line numbers indicated
- Throughput of Scale
  - Need high job volume to test actual time in scheduling. Job should be no-ops.

**Comment by cshamis** [comment]
We had this in the "Kiln" project.  I would like to see it resurrected as an install-option (in the DCOS package?) That builds the Alpha-Omega recipes, and sets up a kiln data generator (could be in a scale clock job?) that produces some dummy data.

You are correct, the point isn't to test processing, but stress-test scale throughput.
