### ISSUE TITLE
Vagrant: error in task [init-examples | Deploy the ace job]

### ISSUE THREAD

**Issue by michaeljohns2** [ngageoint/scale#338]
Unable to run successfully run Scale within Vagrant within CentOS 7 with Ansible 1.9.6 (_does 1.9.x version still matter?_) and Vagrant 1.8.1 and VirtualBox 5.0.20. I hit a few issues prior to the one listed below. I hit them on both the '3.0.0' branch/tag and master, now attempting solely from master.
1. After hitting out of storage issues in VMs, ran `vagrant up --no-provision` to bring up VMs, then ssh to each (scale-master, scale-slave1, and scale-slave2) and ran `btrfs fi show` to verify re-balancing of filesystem chunks was needed, then `btrfs fi balance start -dusage=5 /` to relocate chunks with less than 5% of usage, reference [btrfs troubleshooting here](https://coreos.com/os/docs/latest/btrfs-troubleshooting.html)  
2. After troubleshooting btrfs ran `vagrant up provision` for second attempt, got a failure in task [migrate | migrate db changes] due to docker image '10.4.4.10:5000/geoint/scale:3.0.0-snapshot' not being found. After ssh into scale-master was able to manually fix with `docker tag <scale id> 10.4.4.10:5000/geoint/scale:3.0.0-snapshot`. Another `vagrant up provision` made it past with something like the following: TASK: [migrate | migrate db changes] *****************************************\* 
   <127.0.0.1> REMOTE_MODULE docker command=migrate docker_api_version=1.20 state=started image=10.4.4.10:5000/geoint/scale:3.0.0-snapshot
   changed: [scale-master] => {"ansible_facts": {"docker_containers": [{"Id": "6c76d8f37440123fdd57b3672e36e975db69418cc52c1219a26aa61c3de0b337", "Warnings": null}]}, "changed": true, "containers": [{"Id": "6c76d8f37440123fdd57b3672e36e975db69418cc52c1219a26aa61c3de0b337", "Warnings": null}], "msg": "started 1 container, created 1 container.", "reload_reasons": null, "summary": {"created": 1, "killed": 0, "pulled": 0, "removed": 0, "restarted": 0, "started": 1, "stopped": 0}}
3. However, `vagrant up provision` now is stuck on task [init-examples | Deploy the ace job] with the following issue:
   TASK: [init-examples | Deploy the ace job] ***********************************\* 
   <127.0.0.1> REMOTE_MODULE command /scale/bin/goscale jobs deploy chdir="/scale/dockerfiles/examples/ace"
   failed: [scale-master] => {"changed": true, "cmd": ["/scale/bin/goscale", "jobs", "deploy"], "delta": "0:00:00.067436", "end": "2016-06-15 15:57:10.853385", "rc": 2, "start": "2016-06-15 15:57:10.785949", "warnings": []}
   stderr: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal 0xb code=0x1 addr=0x10 pc=0x46dbbf]

goroutine 1 [running]:
panic(0x8d23e0, 0xc82000e0e0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.HandleAction.func1(0xc820121e08)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/app.go:474 +0x417
panic(0x8d23e0, 0xc82000e0e0)
    /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/ngageoint/scale/scale-cli/vendor/github.com/ngageoint/scale/scale-cli.GetJobTypes(0xc820144a60, 0x17, 0xc8201a65d8, 0x3, 0x0, 0x0, 0x0, 0x7f3c50cd0e50, 0xc820112d50)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/ngageoint/scale/scale-cli/jobs.go:103 +0x51f
main.jobs_deploy(0xc82000d2c0, 0x0, 0x0)
    /scale/src/github.com/ngageoint/scale/scale-cli/cmd/goscale/jobs.go:453 +0x1047
reflect.Value.call(0x828640, 0xa41788, 0x13, 0x963f00, 0x4, 0xc820121d68, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x828640, 0xa41788, 0x13, 0xc820121d68, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.HandleAction(0x828640, 0xa41788, 0xc82000d2c0, 0x0, 0x0)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/app.go:483 +0x2ee
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.Command.Run(0x9666b8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa1b8c0, 0x59, 0x0, ...)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/command.go:186 +0x1301
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.(_App).RunAsSubcommand(0xc820001800, 0xc82000d040, 0x0, 0x0)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/app.go:357 +0x10d5
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.Command.startApp(0x967420, 0x4, 0x0, 0x0, 0xc82010e8b0, 0x1, 0x1, 0x9c82c0, 0x19, 0x0, ...)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/command.go:273 +0xa30
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.Command.Run(0x967420, 0x4, 0x0, 0x0, 0xc82010e8b0, 0x1, 0x1, 0x9c82c0, 0x19, 0x0, ...)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/command.go:74 +0x7b
github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli.(_App).Run(0xc820001680, 0xc82000a240, 0x3, 0x3, 0x0, 0x0)
    /scale/src/github.com/ngageoint/scale/scale-cli/vendor/github.com/codegangsta/cli/app.go:237 +0xa9c
main.main()
    /scale/src/github.com/ngageoint/scale/scale-cli/cmd/goscale/main.go:110 +0x10fd

FATAL: all hosts have already failed -- aborting

**Comment by cshamis** [comment]
Do we have a blurb in the docs stating Mesosphere DCOS CE is the preferred install?  The vagrant scripts seem crusty.

**Comment by gisjedi** [comment]
We are no longer supporting the vagrant/ansible configuration, but will be shortly updating our quick start documentation to encompass installation to both a local environment (DCOS-Vagrant) in addition to the currently documented AWS environment. This is being done under #620 and #766.
