### ISSUE TITLE
Vagrant up fails on "master"

### ISSUE THREAD

**Issue by mchendricks1** [ngageoint/scale#35]
I performed a git clone of "master" today and ran the vagrant related commands to run against VirtualBox on Mac OS 10.11.

ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
Vagrant 1.8.1
VirtualBox 5.0.10

However, it's failing.

The first failure was a typo at the bottom of this file:
scale/ansible/group_vars/vagrant - line 55: 
# These are for the example database
nfs_server: "{{ mesos_master_ip }}""

The second double quote. I fixed that and re-ran vagrant up.

TASK [scale-configs : Install local_settings.py] *******************************
task path: /Users/marshall/DEV/GEOINT/scale/ansible/roles/scale-configs/tasks/main.yml:8
fatal: [slave2]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleFilterError: |password_hash requires the passlib python module to generate password hashes on Mac OS X/Darwin"}

Which might be something I can fix, so I will dig into that error message.

**Comment by tclarke** [comment]
First issue seems to be a merge issue or similar on my part. I'm not seeing the passlib error on my mac so it might be ansible version specific. I did fine [this](https://github.com/ansible/ansible/issues/11244)  You can try doing a `pip install passlib` and see if that fixes it.

**Comment by mchendricks1** [comment]
Yes, that's what I wound up doing myself as well and that addressed that issue. However I am running into this other problem. As it's continuing to startup it hits this issue:

ASK [build-scale : Copy built files to the docker directory] ******************
task path: /Users/marshall/DEV/GEOINT/scale/ansible/roles/build-scale/tasks/main.yml:101
fatal: [master -> None]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh '/usr/bin/ssh -i /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"/scale/scale\" \"127.0.0.1:/scale/dockerfiles/framework/scale\"", "failed": true, "msg": "Warning: Identity file /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key not accessible: No such file or directory.\nssh: connect to host 127.0.0.1 port 2222: Connection refused\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", "rc": 255}

-----
When I run "vagrant up" the second (or third time) then it skirts past this issue. I assume it's a timing error because the file does exist by the time I see that error printout and check, but perhaps not before whatever code is expecting to be there.

**Comment by tclarke** [comment]
I haven't seen that issue either. It does seem like a timing issue. Try initially doing a `vagrant up --no-provision` to bring the machines up then either `vagrant provision` or manually run ansible-playbook and see if that makes a difference.

**Comment by mchendricks1** [comment]
So I tried going the ansible-playbook route but I'm getting this error.

TASK [build-scale : Create scale folder] ***************************************
ok: [master]

TASK [build-scale : Install scale] *********************************************
changed: [master]

TASK [build-scale : Install python build libraries] ****************************
fatal: [master]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

TASK [build-scale : Copy built files to the docker directory] ******************
task path: /Users/marshall/DEV/GEOINT/scale/ansible/roles/build-scale/tasks/main.yml:101
fatal: [master -> None]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh '/usr/bin/ssh -i /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"/scale/scale\" \"127.0.0.1:/scale/dockerfiles/framework/scale\"", "failed": true, "msg": "Warning: Identity file /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key not accessible: No such file or directory.\nssh: connect to host 127.0.0.1 port 2222: Connection refused\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n", "rc": 255}


And what's weird is that it makes it pretty far, however, this "changed" state seems to leave it in a bad way. I can `vagrant ssh master` though so the SSH daemon isn't down(-ish). I feel like the error is that the rsync shell command is not in the host/container it thinks it should be and that's why it can't find the file. As far as I can tell the file exists at the proper time and location. And the VM is running and reachable.

**Comment by mchendricks1** [comment]
Just noticed your comment about ansible versions and remembered a line in the README about ansible 1.9 and that I have 2.0 installed. So I downgraded to 1.9.4, however, the same problem arose.

TASK: [build-scale | Copy built files to the docker directory] **************** 
failed: [master -> master] => {"cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh -i /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"/scale/scale\" \"vagrant@127.0.0.1:/scale/dockerfiles/framework/scale\"", "failed": true, "rc": 255}
msg: Warning: Identity file /Users/marshall/DEV/GEOINT/scale/vagrant/.vagrant/machines/master/virtualbox/private_key not accessible: No such file or directory.
ssh: connect to host 127.0.0.1 port 2222: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]


FATAL: all hosts have already failed -- aborting

**Comment by tclarke** [comment]
I've found the problem. I'll push a fix tonight.

**Comment by mchendricks1** [comment]
Excellent. Give me a heads up please when I can update. Thanks!

**Comment by tclarke** [comment]
Closed by f49f278de084cca0894158dac613826f7ae32147
