### ISSUE TITLE
Nodes need better self-cleanup after jobs.

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#36]
Many post steps are leaving trash behind on the node.  They need to be better at cleaning up after themselves, or we need a "maid" task to come through every so often to clean house.

**Comment by dfaller** [comment]
Yeah, sometimes they fail. This might be OBE once we change Scale to be fully dockerized and use Docker volumes for our algorithms. The cleanup procedure then might be as simple as deleting a Docker container/volume. For now, nodes can be manually cleaned up by deleting directories for old job executions under the /scale_data directory. This should be revisited after the full Dockerization (like the sound of that!)

**Comment by dfaller** [comment]
This issue is replaced by #219.
