### ISSUE TITLE
Parse_results documentation cleanup

### ISSUE THREAD

**Issue by PARdonMeTech** [ngageoint/scale#369]
The results manifest parse_results section contains confusing references on inputs and outputs, which need to be cleaned up.

parse_results should clarify that it is referencing output_data created in the same job, and that the "filename" corresponds with the output_data file "path" contained in the same results manifest file. 

Some recommended new language:

parse_results: JSON array
The parse_results is an array of JSON objects that contain information for associating meta-data with output_data files of a parsing algorithm contained in the same job. Each of the parse results corresponds to an output_data of the type “file”.  The parse algorithm / job must operate before a trigger, and after a data ingest (on "source" data).  The data_type array allows you to assign labels to data that can be used to trigger recipes based on the data_type values assigned by the parsing job.  Multiple data_type labels may be assigned to a file.  (Triggers require a file have all of its required labels, but a file may have more labels than are present on the trigger).  One output is required for every "file" output in the output_data section.

A “source” file is something that was provided by an ingest process. Files produced by data processing algorithms are known as “product” files. As an algorithm developer, this is not important, but when you are tying an algorithm to the scale data, this distinction is important. Each parse_results object has the following fields:

filename: JSON string
The filename is a required JSON string that correlates to an output file in the results manifest.  It has the value of the path in "output_data" { "file": { "path": value }}.  It is an output of the parsing algorithm.

**Comment by dfaller** [comment]
This is incorrect. The parse results for a job are referencing an input file, not an output file. The idea is that a job may provide additional parse info to Scale about one or more of its input files. Parse results for output files would be unnecessary because you can specify file meta-data with the output file in the results manifest.

**Comment by PARdonMeTech** [comment]
The term "input file" was very confusing to me personally.  My understanding based on conversation with Trevor R.H. Clarke is that it refers to an output of the job that is performing the parse action and generating the results manifest, so for every parse_result, there is an output_file referenced in the results manifest.  If it is an "input_file" as far as Scale goes, that makes sense, but the logic train is very confusing when it's referred to as an "input_file", because it is an output of the job that performs the parsing.  If that is all accurate, I'd recommend clarifying the language between an "input" for a job (whether as part of a parse or an algorithm), and an "input" to scale, rather than using the generic term "input_file".  That said, I'm by no means an expert on scale & could very well be confused.

Meta-data tagging as I understand it is only available for geo-coords (per the docs here: http://ngageoint.github.io/scale/docs/algorithm_integration/results_manifest.html).  This was in reference in particular to parse trigger labeling / data tagging through using the "data_types"

Discussion on this topic is in the most recent gitter thread.
