### ISSUE TITLE
Exit codes from jobs seem to be getting lost

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#37]
Exit codes from pre and post are ok, but execution status of the job itself doesn't seem to be making it out of the docker container.  Are we not sending it correctly or are we losing it? Or is this just a display bug?

**Comment by dfaller** [comment]
We need to see what (if anything) is getting populated in the job execution record. For one of your examples, can you look at the job execution record (job_exit_code field) or click on a job execution in the UI (job detail -> executions tab) to bring up the table of job execution values. Is the job exit code getting populated?

**Comment by dfaller** [comment]
This issue is OBE.
