### ISSUE TITLE
Pass Docker Credentials

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#370]
Update Scale to be able to pass Docker credentials to Mesos. This will allow Scale to launch jobs based on images in Docker repositories that require authentication.

**Comment by gzehring** [comment]
Mesos has documentation for passing credentials for a private docker repository, but it appears to not support credentials on a task basis. Here is a link to that documentation [](http://mesos.apache.org/documentation/latest/docker-containerizer)/
