### ISSUE TITLE
Create a tool to fake a strike ingest of existing data

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#38]
Create a tool (command line is fine) to generate database entries for existing ingested data. This should create the file entries like strike does so that existing data from another scale instance can be ingested without having to copy it into the ingest directory again.

**Comment by cshamis** [comment]
Doggonit Trevor.  Have you been reading my mind?  I was just talking to Derick about this yesterday!

**Comment by tclarke** [comment]
So, what needs to end up in the database? It's pretty easy to add the file entries but I don't think they will be very useful without parse entries as well. The problem is, kicking off a parse job will attempt to move the files to a new location unless they already exist in the scale 3 directory layout and a parse job will also kick off automated algorithm jobs on the data. We could probably come up with a scheme to run the parse without moving the files using a separate job type. There would need to be additional special sauce to skip the other jobs after parse.

I don't think we want ingest records as it will show a massive ingest in the stats when you add existing data.

**Comment by cshamis** [comment]
If the directory location is the stumbling block... We can fake that with symlinks.  

-C.
