### ISSUE TITLE
Perform Database Setup in Scheduler

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#399]
Add in command line calls to Django migrate and load_all_data to the scheduler command, prior to starting up the Mesos scheduler driver. This will ensure that the database is up-to-date every time that the scheduler is started, and removes this burden from deployment.

**Comment by tclarke** [comment]
I don't see a burden on deployment. This only requires that the INIT_DB env var be passed when starting the scheduler container. load_all_data should only be called once when the db is initially setup as an admin may modify some of the default data (for example, to change the memory requirements of strike) and load_all_data will revert this back.

**Comment by dfaller** [comment]
This is on hold until we design a better path forward.

Future goals are:
- remove the INIT_DB env var to simplify deployment
- move model inserts/updates from load_all_data fixtures into the scheduler initialization process (so changes by users aren't overwritten)
- ideally split scheduler and rest server into separate containers (for appropriate process handling and load balancing)
- design a partial rolling update for deploying changes to a running cluster

**Comment by dfaller** [comment]
Web link with suggestions on Django migrations: [Link](http://pankrat.github.io/2015/django-migrations-without-downtimes/)

**Comment by dfaller** [comment]
This issue is OBE.
