### ISSUE TITLE
Update Mesos interface install

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#406]
Update the Mesos interface install in the Scale Dockerfile:

Install mesos.interface >=0.28,<0.29 in the dev_win.txt, build_linux.txt, and prod_linux.txt requirement files
Build Mesos egg for 0.28 (need to figure out how we get these, do we build them ourselves?)

Make sure that the final built image connects to Mesos and runs correctly (perform a full integration test) before creating a PR.

**Comment by gisjedi** [comment]
OBE... We don't need native interface anymore.
