### ISSUE TITLE
AWS Region Environment Variable

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#407]
Use an environment variable that gets passed into the Scale Docker container to set the AWS region for the boto3 library. This will require sending that env var to each system task along with the database env vars.

Also set the default region in the storage/settings.py to the 'us-east-1' region.

**Comment by gisjedi** [comment]
This also overlaps with a need to provide configuration for the authentication / endpoints for custom regions in https://github.com/ngageoint/scale/issues/1014.

**Comment by dfaller** [comment]
This requires an update to the configurators to set the env var for system tasks (including pre/post tasks).

**Comment by gisjedi** [comment]
This issue is OBE as we allow specification of region on the workspace and on strike.
