### ISSUE TITLE
Nodes UI

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale#410]
The nodes UI needs the following fixes:

* The node ID isn't passed to the details page when clicking on a row
* The pause button should toggle based on whether the node is paused or not
* Clicking the pause/play button should produce feedback so the user knows what is happening
* Render the datagrid using the nodes API, and then fill in the online/offline labels when the node status API finishes
* Sort the nodes by hostname ASC by default

**Comment by dfaller** [comment]
Instead of the timestamp columns, display the failed and completed counts when the /nodes/status/ API call returns. If possible, display the job exe icons like before in a column, if not then display the running count.

**Comment by ericsvendsen-mil** [comment]
Once we can confirm that pausing/resuming nodes works as expected (due to the 500 error I was receiving earlier), I will submit a PR for this.

**Comment by dfaller** [comment]
I pushed a bug fix for the node patch API.
