### ISSUE TITLE
UI API prefix version

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale#411]
Hardcode the version to each API call in the UI (e.g. `v3`).  That way when new API versions are introduced, the UI can be upgraded incrementally.

**Comment by dickmancj-mil** [comment]
For a balance of configurability, maintenance and performance, considering supporint ability to overrides specific top-level REST service endpoints. Example:
```
"urls": {
            "apiPrefix": "/api/",
            "overrides": {
                "ingests": "/api/v3/"
            },
            "documentation": "/docs"
        },
```
This overrides apiPrefix for all calls to the "<api-root>/ingests" endpoints including /ingests/ and /ingests/<id>/  This wouldn't support overriding only one or the other.  Would this be enough configurability @dfaller ?
