### ISSUE TITLE
Add fields to Job Details

### ISSUE THREAD

**Issue by dickmancj-mil** [ngageoint/scale#430]
Requested fields are:

1. Duration (same as on Jobs list)
2. If executions, Node of last execution
3. If executions, Exit code of last execution

**Comment by dfaller** [comment]
I would recommend that this replace the current timeline section of the job detail page. It can have a breakdown of each task from the most recent job execution with the start, stop, and exit code of each task. Should also include queued time/duration for the most recent job execution.

**Comment by dfaller** [comment]
PR #451 closes #430
