### ISSUE TITLE
Re-deploy logstash and database

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#441]
The current Scale deployment assumes that the scale-logstash application has not been deployed, which is an incorrect assumption. Update the deployElk.py script to destroy the scale-logstash application if it already exists before deploying it. Also destroy and deploy the database if DEPLOY_DB is true.

**Comment by tclarke** [comment]
Is redeployment necessary? This is consistent with the database deployment...use an existing deployment if it's there, otherwise deploy. If you need to deploy, destroy this existing one first.

**Comment by dfaller** [comment]
Pros and cons to destroying and re-deploying scale-logstash each time or just querying and connecting to existing one. One of the advantages to destroying and re-creating is that any changes to how scale-logstash gets deployed gets applied on a Scale deploy.

We want Scale to be able to handle everything itself so the user doesn't have to know/remember to destroy scale-logstash.

**Comment by tclarke** [comment]
Then we should do the same thing with the scale-db for consistent behavior. Suggest changing this issue to include both.

**Comment by dfaller** [comment]
That's fine. It can also destroy/re-create the database app if DEPLOY_DB is true.

**Comment by dfaller** [comment]
I'm closing as this has been rolled into issue #442
