### ISSUE TITLE
Deployment / Architecture Documentation

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#443]
Provide robust logging documentation explaining that Scale requires ElasticSearch to be set up separately and direct the user to ElasticSearch's docs for more details. Explain the use of the DEPLOY_LOGGING, SCALE_ELASTICSEARCH_URL, SCALE_LOGGING_ADDRESS, and LOGSTASH_DOCKER_IMAGE environment variables.

**Comment by gisjedi** [comment]
We need to migrate a bunch of the deployment details and specifics of how Scale exists within DC/OS to the documentation from the README. Logging is just one part of that. We need to cover the following things at a minimum:

- What the primary architectural components of Scale are.
- What external dependencies we have.
- Minimal testing configurations vs optimal production configurations.
- Detail on the available Docker environment variables and what they actually mean.

**Comment by gisjedi** [comment]
Add some documentation pertaining to getting a development environment up and running.
