### ISSUE TITLE
Environment variables for Scale REST API server

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#459]
Add two new environment variables to handle the following settings related to the Scale REST API server:
1. An env to control the number of gunicorn workers (-w arg which we currently set to 4, which is a small default)
2. An env to specify the timeout threshold for REST API HTTP requests. This would need to affect both gunicorn and Apache.

**Comment by gisjedi** [comment]
The stack mentioned in this issue is somewhat out-of-date (using mod_wsgi with apache now), but the desired functionality is still relevant - environment configuration of worker count and API timeout.

**Comment by gisjedi** [comment]
I'm going to mark this OBE as API cleanup is ongoing to reduce need for high timeouts. Workers can already be upped by increasing the number of CPUs allocated to the web server (`SCALE_WEBSERVER_CPU`).
