### ISSUE TITLE
Using get_log_json JobExecution method sets hard cap of 10,000 messages

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#463]
We need either a configuration value or a parameter (preferred) to allow increasing the hard-coded maximum of 10,000 log messages.  JobExecution.get_log_json can be found in job/models.py.

**Comment by dfaller** [comment]
With tailing, you can get the entire log. This just needs a doc update to explain that 10,000 is the max for a given log request and the user can continue from the last second in the response.
