### ISSUE TITLE
Replacing dashboard dials on overview

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#469]
The dashboard dials have some issues. 

A) they look a little dorky.  
B) they query Mesos as a "whole", which can become confusing and less meaningful if more that one framework is running on the mesos cluster.  
C) Moreover, they do not indicate how much "as-tasked" specifically by the Scale instance you're viewing.
D) Nodes "paused" by Scale (for whatever reason) are still counted, even though they are not "taskable" by Scale; this misrepresents the resource utilization metrics... which aren't being captured anywhere.

To fix I suggest:

New graphical display... (something other than speedometer style dials) (pie charts?  side by side bar charts?  tracking line charts (if we have hysteresis) ...
Display three metrics for each CPU, RAM and Disk : mesos-used, mesos-free, and resources used by (this) scale.
A poor man's "estimate to empty" the queue would be nice too.  Even if it's only a current jobs per hour/size of queue adjusted for current rate new jobs are coming in.

**Comment by dfaller** [comment]
This is OBE due to the upcoming new Scale UI.
