### ISSUE TITLE
Investigate Mesos node outage

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#487]
Investigate why Mesos takes a long time to recognize offline nodes.
This appears to take much longer than the configured timeouts for the agents.

**Comment by gisjedi** [comment]
This is a result of poor DCOS / MESOS default to rate limit agent removal (https://issues.apache.org/jira/browse/MESOS-7721 and https://issues.apache.org/jira/browse/MESOS-5948) and agent removal timeouts. This causes serious problems when scaling in operations are performed. The result is that if huge swaths of agents go unreachable, a lot of tasks can be hung until they catch up. The best practice here is to set the MESOS_SLAVE_REMOVAL_RATE_LIMIT configuration setting to `None`.
