### ISSUE TITLE
Investigate ES Reliability on DC/OS

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#488]
Investigate ways to run ElasticSearch on DC/OS reliably. If ES executors come back up on different nodes, the entire set of data can be lost.

**Comment by gisjedi** [comment]
Rexray does support creation of EBS volumes that will ensure data persistence through machine shutdown. Rexray is a complete pain to get working, but DC/OS 1.8.4 has it built in. I've verified that simply adding the argument "--externalVolumeDriver rexray" to the Elasticsearch Marathon app configuration will get ES storing data to EBS.

This requires all nodes be configured with an appropriate IAM policy to allow EBS volume management.

The following IAM role will accomplish that:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteVolume",
                "ec2:AttachVolume",
                "ec2:DetachVolume",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumes"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

**Comment by gisjedi** [comment]
Pitfalls discovered:

- Volume cleanup is not performed and name collision is possible. The volumes are named with the format: "[frameworkname][id]node". _frameworkname_ is by default always "elasticsearch". _id_ is a sequence number between 0 and n-1, where n is the number of Elasticsearch nodes specified. 
- On a reinstall of DC/OS from the provided CloudFormation templates a new subnet will be created that will not have accesss to any previous volumes. This will cause errors if names collide, which they easily will. The solution is to either delete the old volumes or update the _frameworkname_ configured for the Elasticsearch application.
- 2 or more clusters of Elasticsearch are not possible within a single AWS account unless the individual _frameworkname_ values are unique. This is also a result of the above mentioned framework collision.

**Comment by gisjedi** [comment]
I'm closing this for now as we can't really adopt this solution until we fully move to DCOS 1.8. This can be re-opened if further investigation is needed.
