### ISSUE TITLE
Investigate DC/OS Resource Allocation

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#489]
Investigate how DC/OS can be configured/controlled for how it allocates resources between different frameworks. This is important for controlling the resources offered to a dev and prod Scale running within the same DC/OS cluster.

**Comment by mikenholt** [comment]
Configure Mesos to use roles for the frameworks:
- Start mesos-master with ```--roles="scale-prod,scale-dev,marathon,etc..."``` flag.
- Define weights for each role (dynamic): ```--weights="scale-prod=3,scale-dev=2,marathon=1”```
    - This results in scale-prod getting 50%, scale-dev getting 33.3%, and marathon getting 16.6% of resources.
    - If Mesos version is >= 1.0, you need to hit an HTTP endpoint to assign weights (http://mesos.apache.org/documentation/latest/weights/)
- Link a role to a framework at startup: 
    - ```--mesos_role="scale-dev"``` for cli 
    - ```<property> <name>mesos.scale-prod.role</name> <value>scale-prod</value> </property>``` for xml

[Source] (https://support.mesosphere.com/hc/en-us/articles/206474745-How-to-reserve-resources-for-certain-frameworks-in-Mesos-cluster-)

**Comment by dfaller** [comment]
Investigation complete.
