### ISSUE TITLE
Scale logstash should bootstrap off any initial ES node

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#498]
Scale logstash fails whenever the first node of the initial set is down. It should attempt to bootstrap by trying all nodes within the initial set.

**Comment by gisjedi** [comment]
Also need to address issue with http_address field for nodes containing both a hostname and an optional '/' delimited ip:port value.

Following git diff snippet will address:

```
- endpoints.append(node['http_address']
+ address = node['http_address']
+ if '/' in address:
+     address = address.split('/')[1]
+ endpoints.append(address)
```
