### ISSUE TITLE
Latest Execution Bug

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#502]
A bug can occur related to determining the latest execution for a job. Scale currently uses model creation time, but this can be incorrect in cases of unsynchronized clocks. This is a major problem but it can cause the scheduler to fail/cancel the incorrect job execution record and prevent rescheduling of the job.

Update the code to use a more reliable indicator for the latest execution, perhaps highest id. Make sure to find all instances where the latest execution is determined, such as failing/canceling job exes, the REST API, etc.

**Comment by emimaesmith** [comment]
Appears to have been fixed
