### ISSUE TITLE
Eliminate UI build when unchanged to reduce time

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#503]
The majority of build time is spent on the retrieval of NPM packages simply for it to act as a dependency of the gulp task runner that compiles the static artifacts. This could be almost entirely eliminated if we precompiled the UI and stored a hash of all files within the UI source tree for detecting updates. Builds would only be needed on update.

**Comment by dickmancj-mil** [comment]
I added support for "--tag" param on the gulp deploy task. 

Example: gulp deploy
Produces package in file deploy/scale-ui-master.tar.gz

Example: gulp deploy --tag 3.2.0
Produces package in file deploy/scale-ui-3.2.0.tar.gz
