### ISSUE TITLE
Vagrant up errors on docker start

### ISSUE THREAD

**Issue by nstarke** [ngageoint/scale#504]
I see the following output after running `vagrant up`:

```
TASK: [common | docker service] *********************************************** 
<127.0.0.1> REMOTE_MODULE service name=docker state=started enabled=true
failed: [scale-master] => {"failed": true}
msg: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/nstarke/vagrant.retry

scale-master               : ok=14   changed=13   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

I then `vagrant ssh scale-master` and run `systemctl status docker.service`:

```
[vagrant@scale-master ~]$ service systemctl status
Redirecting to /bin/systemctl status  systemctl.service
● systemctl.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[vagrant@scale-master ~]$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2016-09-30 01:22:51 UTC; 7min ago
     Docs: http://docs.docker.com
  Process: 4785 ExecStart=/bin/sh -c /usr/bin/docker daemon $OPTIONS            $DOCKER_STORAGE_OPTIONS            $DOCKER_NETWORK_OPTIONS            $ADD_REGISTRY            $BLOCK_REGISTRY            $INSECURE_REGISTRY (code=exited, status=125)
 Main PID: 4785 (code=exited, status=125)

Sep 30 01:22:50 scale-master systemd[1]: Failed to start Docker Application Container Engine.
Sep 30 01:22:50 scale-master systemd[1]: Unit docker.service entered failed state.
Sep 30 01:22:50 scale-master systemd[1]: docker.service failed.
Sep 30 01:22:51 scale-master systemd[1]: docker.service holdoff time over, scheduling restart.
Sep 30 01:22:51 scale-master systemd[1]: start request repeated too quickly for docker.service
Sep 30 01:22:51 scale-master systemd[1]: Failed to start Docker Application Container Engine.
Sep 30 01:22:51 scale-master systemd[1]: Unit docker.service entered failed state.
Sep 30 01:22:51 scale-master systemd[1]: docker.service failed.
```

Host Operating System: Ubuntu 16.04
Vagrant Version: 1.8.6
Ansible Version:1.9.6 (I also tried 2.0.0.2)

Please let me know if you need additional information / output.  Thanks for the help!

**Comment by mchendricks1** [comment]
I'm running into the same problem.

Host OS: MacOS X Sierra (whatever just came out in the last week or so)
Vagrant Version: 1.8.1 (failed) upgraded to 1.8.6 (failed)
Ansible Version: 1.9.2

**Comment by mchendricks1** [comment]
Alright, I think I have figured out the problem:

In docker.service there is a line with INSECURE_REGISTRY, however, that value wherever it's included from does not fully specify the value with a URL.

ExecStart=/bin/sh -c '/usr/bin/docker daemon $OPTIONS \
          $DOCKER_STORAGE_OPTIONS \
          $DOCKER_NETWORK_OPTIONS \
          $ADD_REGISTRY \
          $BLOCK_REGISTRY \
          $INSECURE_REGISTRY'

So I just removed the last line (from /scale/ansible/roles/common/files/docker.service).

**Comment by dickmancj-mil** [comment]
I'm looking into this issue. In the meantime, you might consider using the updated Quickstart guide that's based on Mesosphere DC/OS. http://ngageoint.github.io/scale/quickstart.html

**Comment by gisjedi** [comment]
We are no longer supporting the vagrant/ansible configuration, but will be shortly updating our quick start documentation to encompass installation to both a local environment (DCOS-Vagrant) in addition to the currently documented AWS environment. This is being done under #620 and #766.
