### ISSUE TITLE
Improve Scale DC/OS package

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#507]
Improve the Scale DC/OS package:

1. Have the Scale web server be launched as its own separate app
2. Group all of the Scale pieces (scheduler, web server, logstash, db, etc) as a Marathon group
3. Clean up dcos_cli.py to use good Python conventions
4. Re-write the entrypoint script in Python

**Comment by gisjedi** [comment]
There are a couple challenges here:

- We cannot build multiple images if the Dockerfiles reside at the root of the source tree. Docker Hub automated builds do not allow for customizing the file name that represents the Dockerfile. A possible approach is to place the scheduler Dockerfile within the Scale source tree, but that also seems awkward. If we did a separate UI+StaticDemo / API+Docs / Scheduler+Bootstrap image we'd be getting pretty close. Splitting this way would allow the existing structure to remain with Dockerfiles in /, /scale-ui, and /scale.
- We have no current way to entirely contain all Scale components within a Marathon group. DC/OS packaging does not natively support groups (see https://github.com/mesosphere/universe/issues/569), so would, at best, be stuck with a kludge where the initial app was outside of the group with all bootstrapped apps living within. This kind of defeats the purpose of grouping, if it doesn't apply to everything.
-

**Comment by gisjedi** [comment]
Another alternative is to perform all the builds manually, eliminating the Docker Hub automated builds. This could be done in TravisCI and then the dockerfiles and context passed could be controlled in a more flexible manner.
