### ISSUE TITLE
Migrate REST API to v4

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#536]
Migrate the REST API to v4 to prepare for release 4.0.0.

1. Remove the option to not specify a version in the REST API.
2. The old log API (/job-executions/{id}/logs/) is not available in v4 (return 404). Also update REST documentation to specify that this no longer exists in v4 (it already says it is deprecated).
3. For the job details serializer, v4 does not include the old "input_files" and "products" fields while v3 still does. Also update the REST docs to reflect this.
4. Update the recipe details serializer to have "inputs" like job detail serializer in a v4 version. The v3 version should still have the "input_files" field like job details. Also update the REST docs to reflect this.
5. Update the REST doc overview to mention both v3 and v4 versions of the API.
6. Update the UI to use the v4 REST API. Also update the test JSONs to remove old "input_files" and "products" fields for job details.

**Comment by ericsvendsen-mil** [comment]
@dfaller are these the JSONs you're talking about? If so, it's unclear to me which fields should be removed... https://github.com/ngageoint/scale/tree/master/scale-ui/app/test/data/job-details

**Comment by dfaller** [comment]
Not sure which ones exactly. Chris had done a search and found some with "input_files" still in them.

**Comment by ericsvendsen-mil** [comment]
Hmm.  Looks like [recipe details](https://github.com/ngageoint/scale/blob/master/scale-ui/app/test/data/recipe-details/recipeDetail1.json#L210) have an "input_files" field, but no "products" field.  Should "input_files" be removed from recipe details?

**Comment by dfaller** [comment]
It looks like recipe details was never updated like job details was. We should probably try to do this before end of sprint and release as well. I'll add it.

**Comment by ericsvendsen-mil** [comment]
Added a [new branch](https://github.com/ngageoint/scale/tree/issue-536) and updated the api prefix to include `v4` via d1d8230ec59e041bdd3aad3c9edd74268675da21
