### ISSUE TITLE
Filter Overview Page by Operational Jobs

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#539]
Add a switch on the overview page to display or hide R&D job types.

This might require a REST API change.

**Comment by dfaller** [comment]
Merged into master

**Comment by gisjedi** [comment]
This issue is not actually resolved in the desired fashion. It was intended that you could filter the overview page (home page / dashboard) so as to only see the operational jobs state. We don't want the health display going red over jobs that are in R&D states.
