### ISSUE TITLE
Batch

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#54]
Create the foundation for adding historical batch processing

New Batch model with definition, status (just setup status?), setup_job_id, event_id, title, description, created, and last_modified fields
New BatchJob model with batch_id, job_id (nullable), superseded_job_id (nullable), and created fields
New BatchRecipe model with batch_id, recipe_id (nullable), superseded_recipe_id (nullable), and created fields
Create new system job 'Scale Batch Setup' with a blank implementation
Create a create_batch() method that validates definition schema (currently empty), creates a Batch model, and queues a Scale Batch Setup job

**Comment by cshamis** [comment]
BATCHES might also be a way to schedule a zero-mesos-resource job.  As in... A job that simply dispatches to matlab cluster or ESE or thunder/spark... Scheduler needs to know about it, but it shouldn't "hold open" resources on mesos for what is (essentially) just waiting around for somebody else to finish working.   The "batch" environment may also be a way to tie a bow around externals as well.

**Comment by dfaller** [comment]
Batches are just the mechanism for doing (bulk) manual job creation. There's nothing specific to batches about how many resources jobs take or external dependencies.
