### ISSUE TITLE
Display Total on Metrics Page

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#563]
On the metrics page, when a sum or count type field is selected, display the total for the entire selected range on the side of the graph.

Ex. If someone selects a job type completed count for two months, it will display the total completed count for those selected months on the side (or above or below?) the graph.

**Comment by ericsvendsen-mil** [comment]
@dfaller this was done in #433.  Perhaps we should make the total more obvious?

**Comment by dfaller** [comment]
Ah, I see it now. Yeah, we should make that more obvious.

**Comment by dfaller** [comment]
It would be nice if the total had the unit conversion applied to it as well.
