### ISSUE TITLE
MapReduce-style processing in NGA Scale?

### ISSUE THREAD

**Issue by mchendricks1** [ngageoint/scale#565]
Do jobs and/or recipes support the notion of mapreduce? For example, if I am doing a MRI scan processing and want to process the data in grid cell fashion on multiple computing nodes, collect the set of output files and then get "notified" when the map portion/individual output generation parallel steps are completed? 

Or a super transaction? A transaction of transactions? Maybe there's a better term...

**Comment by dfaller** [comment]
Scale is not currently designed to handle a MapReduce type problem. Our team has worked with solutions we've built on top of Apache Spark for those type of use cases.

Scale is designed around automated batch-type processing where a given algorithm runs entirely on a single node at a time.

**Comment by cshamis** [comment]
That said, Scale *can* be used as the job control mechanism to /submit/ to Spark or Hadoop or whatever.  

Or... you *could* roll your own poor-mans map-reduce/render-farm pattern as follows:

The first job in your recipe (Chipper) could break down the source file into smaller pieces (A, B, C, D...) for child jobs (ChipProcessor A, ChipProcessor B ... ) to work in parallel. Then you would have another Job (ChipAggregator) put all the pieces back together, then another job could publish an RSS notification, send an email, push to a website... whatever, once everything is complete.  The Scale system is flexible enough to do that.  But, as @dfaller said, there are other tools that would do that for you probably easier.

**Comment by dfaller** [comment]
I think the question has been answered, so I'm going to close this issue. Let us know if you need anything else.
