### ISSUE TITLE
Remove Job Type docker_params

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#588]
Remove the docker_params field from the job type model. This is a security concern as it allows an algorithm author to inject arbitrary Docker parameters into their job containers.

Before starting this issue, make sure to implement alternative methods to cover any use cases for this (e.g. configurable settings for job types, setting shared memory size, mounting in extra data).

**Comment by emimaesmith** [comment]
The job_type docker_params field will be removed as part of removing the v5 APIs.

**Comment by emimaesmith** [comment]
Closed via #1534
