### ISSUE TITLE
Ingest Scan

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#589]
Develop a capability for the ingest process to "scan" a workspace already filled with existing files.

**Comment by wardcr** [comment]
This looks like a duplicate of #575

**Comment by dfaller** [comment]
Yeah, though the other issue also talks about ingesting via REST API. When it comes time to implement, we'll grab this or the other item.

**Comment by gisjedi** [comment]
I'm taking this and beginning the investigation on what all is needed to do a full / filtered workspace scan.
