### ISSUE TITLE
Editing Strike from Scale GUI fails on validate.

### ISSUE THREAD

**Issue by antman1p** [ngageoint/scale#593]
When editing a Scale Strike from the GUI. when one clicks validate it gives an "Invalid strike configuration error. {.....} is not of type string."  We have to create a whole new strike in order for our edits to work.

**Comment by dfaller** [comment]
I also ran into the same issue. Here are my notes:

The Strike UI page is submitting an invalid JSON to the create strike API. It appears that it is sending a workspace JSON object instead of just the workspace name string for the "new_workspace" field.
