### ISSUE TITLE
Filter out timeouts from other errors

### ISSUE THREAD

**Issue by wong-j** [ngageoint/scale#599]
The majority of Algorithm errors are due to timeouts.  Can you filter out timeouts from the rest of the Algorithm errors either by making timeouts their own special error category or through the UI somehow with a filter.

**Comment by wong-j** [comment]
Any progress on this?

**Comment by JohnPTobe** [comment]
We'd have to update the API to support this unless we want to just have the UI grep for timeout. It'd be a fairly easy issue to fit in if we want to treat timeouts as a special case. Or perhaps we could allow for filtering out error ids whereas we currently allow only for specifying error ids to include.
