### ISSUE TITLE
Walking ingest record to recipe instance

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#60]
A frequent use-case that occurs is being able to follow ingested files through to the recipes that ran, and (eventually) down to the execution logs.  This is a fairly common task, and is not accomplished easily at present.  

It would be very helpful to have a filename searchbar that filtered the ingest record(s) and also if ingest-records could be made "clickable" to take you directly to the recipe.  Since there may be more than one recipe, a popup with a list of "Which recipe do you want?"  might be in order...

**Comment by cshamis** [comment]
More people are asking for this.  We either need an external companion app that provides a searchable interfaces to ingest table that shows list of all file/job/recipe children, or we need to build into Scale. 

API should, Given (a file) return all child products all the way down, and return any parents all the way up, but don't decend once you go up.  The "super tree" structure returned should have names of files, recipe, date created, date of data, job, prod type, url path, size, and any/all supercedes/deprecates data.  No one else has ever done so much for product generation or tracking and will be a huge feature.

**Comment by dickmancj-mil** [comment]
API now supports file_name filter. UI needs to be updated to call API when user enters a file_name.

**Comment by cshamis** [comment]
Ingest details page looking good.  Now, we need a consistent UI decision for when to follow file/product links to the details page... and when to download them.  I think C. Ward suggested treat all as links but offer a download button ⬇️ next to all listings.  We need to improve being able to "walk" around inside files to recipes to products and back again.
