### ISSUE TITLE
S3 workspace and Strike configuration bug

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#615]
The S3 workspace and Strike configurations should ignore access key credentials and host paths that are set to empty strings. Right now the UI is inserting empty strings into those fields and it is causing the S3 strike to fail.

**Comment by gisjedi** [comment]
For the issue of empty keys for credentials, the current behavior actually is that empty values raise an exception, but empty 1+ length strings do not. I propose that we change this to be whitespace pruned 0 length strings quietly fall-back to role-based auth. Actually missing `access_key_id` or `secret_access_key` should raise an exception as that is a truly invalid `credentials` object.

I'm going to argue that we should fix the UI to not be passing these empty string values as I would prefer are API be able to assume rational values for the `credentials` object, as opposed to having to assume empty values means we should fallback to role-based auth. I'm going to propose a new issue to address this sort of behavior throughout the UI.
