### ISSUE TITLE
Strike Page Fails to Create New Strike

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#618]
The Strike UI page is submitting an invalid JSON to the create strike API. It appears that it is sending a workspace JSON object instead of just the workspace name string for the "new_workspace" field.

**Comment by wardcr** [comment]
This sounds like a duplicate of #593

**Comment by dfaller** [comment]
Possibly, though in my issue I was unable to create a Strike. I'll add my information to the other issue and close this one.
