### ISSUE TITLE
Remove job type is_privileged

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#621]
Remove the ability for job types to run as Docker privileged.

Need to first ensure that all use cases that currently rely on this are successfully handled another way.

**Comment by dickmanp** [comment]
Mounting DTED and SHM are 2 current use cases ...

**Comment by emimaesmith** [comment]
The docker_privileged flag will be removed from JobType as part of removing the v5 APIs

**Comment by emimaesmith** [comment]
Closed via #1534
