### ISSUE TITLE
Fix Ingest Status REST API Slowness

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#637]
The data feed metrics are getting increasingly slow and now the API times out.

Build two models for caching the data feed metrics by hour; one for data time and one for ingest time. The metrics should be binned by hour. The new models should have indexes on their strike and time fields. The models should be created/updated at the following times:

1. Ingest time models should be updated in the same transaction as an ingest model going to 'INGESTED' status.
2. Data time models should be updated in the same transaction as a source file being parsed (when parse results are handled). If the source file is being parsed again (has been previously), do no update if the data time has not changed and decrement the old time bin if the data time is changing.

Update the appropriate ingest REST APIs to query the new models for the results.

**Comment by wardcr** [comment]
Could this be done using the existing metrics system instead of a special-case for data feed? It seems like that might simplify the logic compared to the description in point 2.

**Comment by dfaller** [comment]
No, the existing metrics system won't work. The metrics system is based on days and is only calculated once (you are guaranteed that the results never change).

The data feed metrics are never "done", you could always ingest a file with an older data time. Also, we need the results calculated in real time as ingests and parses occur.

**Comment by dfaller** [comment]
New plan:

Copy the data_started and data_ended fields (from scale_file) to the ingest models as the source files are parsed.
Add appropriate indexes for the way the ingest models are accessed (e.g. ingest_ended).
Re-work the API query to cut out joining the source_file, scale_file, and workspace models.
