### ISSUE TITLE
Thinking about elastic compute for Scale 3

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#67]
One thing we have talked about is adding the "elastic compute" capability to Scale3.  I've thought about this a little and I can see two main cases that this might be highly beneficial... 
A) when the queue is reaches a certain watermark of jobs with a low-latency property.  (which we haven't defined yet, so Derick, take a memo to add a low-latency requirement property to jobs) Low-latency jobs are something that would be capable of requesting more workers through the elastic compute mechanism.  
-OR-
B) when high-priority jobs reach a certain watermark.  

If queued jobs are neither high-priority, nor low-latency then they will simply wait on the stack until resources free up.  Specifically, this would mean jobs like background processing or WES jobs will simply take "as long as it takes" but something like high priority or low-latency jobs might trigger the system to dynamically request more resources, and/or shrink back accordingly.  

This would require adding more brains to the scheduler, and the aforementioned "low latency" property requirement to jobs.

**Comment by emimaesmith** [comment]
closing as OBE
