### ISSUE TITLE
Node Detail Page

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#68]
We need to update the node detail page to give a better understanding of what's happening on a node.
I like the idea of pie charts for each resource type (CPU, mem, disk) that show the breakdown of resource usage by the different job executions currently running on the node. The running job executions could be displayed in a table (paged?) that indicates the color of the executions resources in the pie charts. Or should we just display numbered totals for the job executions grouped by job type?

Some thought will need to be put into this so that consistent information is presented from the API between Scale's view and Mesos' view of what's going on.

**Comment by cshamis** [comment]
Maybe a tabular list that included: 

hostname
number of jobs currently executing
and fuel bars for each:
disk
cpu
ram
% success rate of the node over last 24, 12, 6 hours.

The fuel-bars would represent utilization that particular worker is according to the number and type of jobs currently assigned, subtracted from the available resources of the node. We can do that right? That's not too much to ask (I mean of the API calls and UI threads) is it?  I think fuel bars would act as good compromise between pie-chart, and still be something that looks good on a "per line" basis.

Moreover, clicking on any particular worker-node line would take you to the "currently running" page filtered by that node name. So a user could see exactly what that worker was doing.

I'm closing item  #69 as dumplicate.

**Comment by dfaller** [comment]
Please re-open #69. This issue is for a page displaying the details of a single node, not a node overview such as #69. :)
