### ISSUE TITLE
Add 'Cancel All' functionality to Jobs list

### ISSUE THREAD

**Issue by antman1p** [ngageoint/scale#682]
I have 4900+ queued jobs and currently have to manually cancel each job, one at a time.  Please add functionality where the user can select all and cancel multiple jobs, or a "cancel all" button to the jobs list UI page.

**Comment by dfaller** [comment]
Yes, this functionality is definitely needed.

In the mean time, the following database queries performed together will accomplish what you like, just specify the job type of the queued jobs you want to cancel:

```
delete from queue where job_type_id = ?;
update job_exe set status = ' CANCELED', ended=now(), last_modified=now() where status = 'QUEUED' and job_id in (select id from job where status = 'QUEUED' and job_type_id = ?);
update job set status = 'CANCELED', ended=now(), last_status_change=now(), last_modified=now() where status = 'QUEUED' and job_type_id = ?;
```

**Comment by JohnPTobe** [comment]
This is implemented in the v6 api and v6 ui
