### ISSUE TITLE
Nodes page and scaling to large number of workers

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#69]
Nodes page is useful, but needs to be more scaleable to support larger number of nodes... hundreds if not possibly 1000s of worker-nodes.  A tabular list-view that listed information such as:

hostname
number of jobs currently executing
fuel bars for:
disk
cpu
ram
% success rate of the node over last 24, 12, 6 hours.

The fuel-bars would represent utilization that particular worker is according to the number and type of jobs currently assigned, subtracted from the available resources of the node.  We can do that right?  That's not too much to ask (I mean of the API calls and UI threads) is it?

Clicking on any particular worker-node line would take you to the "currently running" page filtered by that node name.  So a user could see exactly what that worker was doing.

**Comment by cshamis** [comment]
Dumplicate of #68

**Comment by dfaller** [comment]
Clicking on any particular node line could take you to a node detail page which (among other things) could have the running  job executions.

**Comment by dfaller** [comment]
This is actually not a dupe. The node detail page is for displaying a single node. This issue talks about the page display all nodes (or an overview of nodes). I would recommend re-opening. :)

**Comment by cshamis** [comment]
Can't we just factor all this into one item?  If we capture the "complete" user story in #68 then we shouldn't really need #69...  Now, for a specific bug report or a feature "tweak" then it makes sense to be as specific as possible, but we're talking about a more "fundamental rethink" for the whole nodes page concept.  

But I can go either way.

-C.
