### ISSUE TITLE
Pass Docker credentials in Docker Pull Task

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#707]
Update the Docker pull task to use the DC/OS Docker credentials if they are defined. Otherwise the pull task will not use the Docker credentials and potentially fail.

**Comment by gisjedi** [comment]
If we are performing this within a Mesos task per node, we will need to use the Scale environment variable CONFIG_URI to pass a URI into the Mesos task. This URI is expected to contain a package with the following structure:

```
.docker
.docker/config.json
```

The `docker/config.json` file must contain the credentials to the registry where you Scale jobs and algorithms are stored.

Once this package has been expanded, all that is needed to activate the use of these credentials is to tell the Docker CLI where your config directory is:

```bash
export DOCKER_CONFIG=`pwd`/.docker
```

Now `docker pull` operations will use the credentials stored within.
