### ISSUE TITLE
Refactor database file records

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#708]
Refactor how source and product files are stored in the database. This is necessary to improve REST API performance related to searching through source and product files.

**Comment by cshamis** [comment]
APIs for product files need to be able to support fastest possible retrieval, even as product catalog becomes enormous for the following:

get products by created date, data date.
get products by geolocation and date range
get products by batch id
get products by job id
get products by job type and date range
get products by source file
get products by last updated
get products by recipe
get products by recipe type and date range
get products by supercedes and date range
get products by superseded and date range
get products by parsed metadata json keymatch and date range

**Comment by dfaller** [comment]
I created a new issue ([710](https://github.com/ngageoint/scale/issues/710)) for the product REST API filtering.
