### ISSUE TITLE
Products REST API Filtering

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#710]
Make sure that the products REST API allows efficient filtering of the following:

get products by created date, data date.
get products by geolocation and date range
get products by batch id
get products by job id
get products by job type and date range
get products by source file
get products by last updated
get products by recipe
get products by recipe type and date range
get products by supercedes and date range
get products by superseded and date range
get products by parsed metadata json keymatch and date range

**Comment by JohnPTobe** [comment]
This is OBE as Products API is deprecated in V6
