### ISSUE TITLE
Import/export Page

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#72]
We need a UI page for importing/exporting Scale configuration.

**Comment by cshamis** [comment]
Allow exporting to support 'cloning' a config from one scale instance to another directly would also be nice.  Just allow the config to be streamed via rest API as well as unpacked from a file.  This would be Good for backups, migrations, major upgrades, or even just when one group wants to 'transition' a recipe chain from one organization to another.  Being able to move an entire recipe from x to y via one click transfer would be insane!  Govies heads would explode!

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
