### ISSUE TITLE
Error creating a new workspace when an existing one is selected

### ISSUE THREAD

**Issue by tclarke** [ngageoint/scale#733]
1. In the workspaces GUI, select an existing workspace
1. hit Create Workspace.
1. the existing workspace will show up in edit mode instead of creating a new workspace

Workaround is to hit Cancel which deselects the workspace, then hit Create Workspace again.

**Comment by ericsvendsen-mil** [comment]
What version of Scale are you using?  This doesn't seem to happen in 4.2:

![workspaces](https://cloud.githubusercontent.com/assets/15909071/23370004/3cdda902-fce1-11e6-9549-92f310bda863.gif)

**Comment by tclarke** [comment]
I'm using master with chrome.

**Comment by ericsvendsen-mil** [comment]
Hmm.  I'm unable to reproduce this issue, in any browser, in either MacOS or Windows.
