### ISSUE TITLE
Indicator of which jobs have already been viewed

### ISSUE THREAD

**Issue by bowmanmc** [ngageoint/scale#741]
Algorithm developers are starting with a big list of jobs, then going to the details view in each one. They then sometimes forget which jobs they've viewed. It's frustrating for them when they are going through a large list of jobs.

- Maybe we can show job details and list at the same time?
- Maybe a short lived cookie to indicate which jobs have been viewed recently?

**Comment by wardcr** [comment]
Since I believe job details are using a separate URL, you should be able to use the CSS :visited selector to style the links to previously viewed pages pretty easily.
