### ISSUE TITLE
Need a recipe view for trigger events

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#75]
User will need a way to see how ingest, parse, and file creation trigger events are "wired" up.  

Options include: 
A visual like the recipe view tree would work, but some care should be taken to differentiate it slightly in style to set it triggers apart from "jobs" in recipe view.  Different color scheme, or shapes, or maybe just hollow "outlines" for events might work?  

We could also replace the "start" at the top of each recipe with the name of the trigger that spawns the recipe. It would lend a little more visibility into the ingest parse trigger magic.

**Comment by cshamis** [comment]
We could also replace the "start" at the top of each recipe with the name of the trigger that spawns the recipe.  It would lend a little more visibility into the ingest parse trigger magic.

**Comment by dfaller** [comment]
This is OBE.
