### ISSUE TITLE
Re-queue selected on jobs page

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#76]
Add a button at the top of the jobs page to re-queue the "selected" jobs. The selected jobs are those that match the page filter criteria and reflect the count at the top of the page. Chris S wanted to make sure that it was clear that the button reflects that the button will re-queue all selected jobs. We probably want to make it clear that it will requeue the same number as the count on the page.

Use the new /api/queue/requeue-jobs/ API call which can take a similar set of filter params as getting jobs. The new call can also take (multiple) job_id params so migrate the existing single click requeue buttons to use the new API call (URL change only) and we will remove the old /api/queue/requeue-job/ API call.

As a small aside, please also update the table so it doesn't scroll. We end up getting a lot of double scollbars on the page. The same is probably applicable to the recipes page.

**Comment by ericsvendsen-mil** [comment]
If requeue-jobs is called with a date range, will all jobs within that date range be requeued or only those whose status equals 'FAILED' or 'CANCELED'?

**Comment by dfaller** [comment]
Only those in 'FAILED' or 'CANCELED', but all within the filter params will be returned in the results. I think you might just want to reload the page after the button is clicked.

**Comment by ericsvendsen-mil** [comment]
Ok. Just thinking how to phrase the button text, since the total job count may or may not reflect what will be requeued. All other counts would be per-page only.

**Comment by dfaller** [comment]
Right. The button is being applied to the total count, just some of them might not be applicable. Maybe 'Re-queue All' next to the total count number?

**Comment by dfaller** [comment]
Closed due to being merged into master
