### ISSUE TITLE
Docker parameters for jobs

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#77]
Create a JSON field holding Docker params for the job_type, job, and job_exe models. The job_type field will be a configurable set of Docker params that the algorithm owner wants to have passed to their Docker container. When a job is created, the Docker params JSON will be passed from the job_type to the job (and so on from the job to each job_exe). When the job_exe is scheduled, cache the Docker params JSON in the RunningJobExecution tasks, and use the values to set the Docker parameters when the task is converted into a Mesos Docker task.

Look into how to best show the user what the full Docker command is.

Create follow-on issue for updates to job type, job, and job_exe REST APIs.

**Comment by tclarke** [comment]
The mesos docker executor builds the docker command then logs with VLOG(1). Enabling verbose logging on the slaves should send this to the slave log but will increase logging verbosity significantly. Alternately, we would have to duplicate the code that builds the command line.

**Comment by dfaller** [comment]
Let's test it on the DevNet cluster to see exactly how much logging verbose is.

**Comment by tclarke** [comment]
Awaiting a reply from the mesos list about how to enable that logging level. For now, I'm pushing the rest of the code for review.
