### ISSUE TITLE
Recipe Names in Product Paths

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#78]
Add recipe name and version into the paths used to store products in workspaces.

Consider recipe and job name collisions.

**Comment by cshamis** [comment]
The parser is what 'suggests' the storage path to the workspace.  This doesn't sound like strictly a scale thing, but a how you want your parser to parse thing.  Or am I missing something?

**Comment by cshamis** [comment]
I think we're coming around to the fact that we'll /never/ be able to decide how to do the products directory hierarchy.  
Feed/recipe/job/date/exe might be right for some, wrong for others.  And date?  Ingest time or data date?  Maybe we might want feed/recipe/job/date/lat-lon/ 
We *could* do something like have the job define one or more 'logical path' from a template in job definition and automatically build symlinks in the workspace to the physical location (feed/job/datadate/exe). -OR- we could build a WebDAV on the fly napped to the physical.

**Comment by dfaller** [comment]
This would add a ton of complexity for no benefit. The bottom line is that algorithms and users should not care at all what the file path is. Indeed some storage systems (like S3) are going to have performance characteristics that require letting the storage system have control over all or part of the path. Browsing through the storage like a file system to "find" files is an outdated solution. We may not even be able to do this in S3 with even close to good performance. If something outside of Scale wants to access a large number of files, it should query a REST API that can return the appropriate paths/links for the algorithm to access the files it wants. I think creating a base path with things like recipe and job name is still useful because the storage backend may have some benefit to grouping the products that way.

**Comment by cshamis** [comment]
Well... the algorithm developer shouldn't know I agree with you there, but
as a Scale admin, you might have an opinion to how and where things are
stored in the product archive.  Up to and including LAT/LON and the other
things... using a token expansion system to build the product path is a
trivial search and replace.  Hardly a ton of complexity.

But you raise a point, is it the Scale system's job to publish product
information yes/no?  If no, then this doesn't matter.  If Yes, then what is
the obligation?  In the case of S3, then Scale might not

**Comment by dfaller** [comment]
Scale does "publish" product information through the REST API.

The Scale admin shouldn't care about "where" the file is. It doesn't matter. It's some arbitrary string that needs flexibility to work with different storage systems. If you are trying to "search" for files using the file system, it will be much easier and more accurate to use the REST API. Looking at the file system you can't tell if a product is superseded or even published.

Allowing job types and recipe types to have independently configurable paths may not be a ton of additional complexity, but it's unneeded. Having multiple parallel file systems using symlinks is a lot of extra complexity and the REST API solves the problem in a better way.

**Comment by dfaller** [comment]
Chris S,

We have a question about how to resolve recipe type and job type name collisions when adding recipe information into the product paths. The situation arises when you have a recipe type name that is the same as the name of a job type that isn't in a recipe. So say you have recipe type 'foo' and job type 'foo' and job type 'foo' is used outside of a recipe. They would both put products in the same top level directory which would be confusing. Chris W suggested using 'recipes' and 'jobs' prefix directories, giving you this instead:

Recipe Type 'foo' products go here:
/recipes/foo/1.0/jobs/bar/1.0/...

Job Type 'foo' products go here:
/jobs/foo/1.0/...

I think this is the most straightforward and cleanest solution. What do you think? Do you want John's input?

**Comment by cshamis** [comment]
Well, OK, the symlinks idea was nutty.  

But, what about the WebDAV idea?

WebDAV is a REST endpoint.  And it would make some things very easy for downstream folks.  We could present file data in a multiple of ways, by date, by recipe, by job.. Etc...

-C.

**Comment by cshamis** [comment]
Well... WebDAV is a REST endpoint.  :-). And it would make some things very easy for downstream folks.  We could present file data in a multiple of ways, by date, by recipe, by job.. Etc...
…

As for Chris W suggestion, it's solid, and clean.  Are we deciding to abandon datadate and exe_id?  Without exe_id subsequent executions of the same 'Job' would overwrite their products.  --Not sure that's a problem, since (assuming the job sucesfully ended) it should produce the same output...  If either recipe version or job version change then there's a new path... So that works... 

It's good, but part of me feels like we should be using sym links or hardlinks to map the products both to recipes and jobs data date and ingest date.  All posix file systems can do that.  And S3 supports multiple "tags" so it can do it too... And yet, I get the "just query the API" method too.

I want to think about this some more.

**Comment by dfaller** [comment]
No, we're not abandoning the data date and job_exe directory. Those are part of the '...' in my example directories. I was just omitting them for simplicity. We'll go ahead and add the recipes and jobs directories for this issue.

**Comment by cshamis** [comment]
Ok.  Then I think that's good.  But I am confused a bit.  Is the job_exe_id the job_id or the execution_id?

**Comment by dfaller** [comment]
Job execution ID.
