### ISSUE TITLE
Set Operational Status at Recipe Level

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#80]
Add capability to mark an entire recipe as operational/R&D.

Consider solutions:
1. Add is_operational field to recipe_type. A job creates R&D products if either its job_type or recipe_type has is_operational == False.
2. Convert is_operational into a job data field (job_type field would be default). Decide if recipe_type has a field or if recipe data has field.

Might also be worth considering at this point implementing operational/R&D status at the output (product) level.

Also is_operational is missing from the documentation for the edit job type REST API.

**Comment by cshamis** [comment]
Is this on recipe type? Or instance or both?  I think both is best.

**Comment by Fizz11** [comment]
Closing all issues > 2 years old.
