### ISSUE TITLE
Update batch details to include associated recipes, jobs, and products

### ISSUE THREAD

**Issue by ericsvendsen-mil** [ngageoint/scale#803]
This will allow adding links to associated items from the batch details UI.

**Comment by dfaller** [comment]
On the batch detail page, create tables for the batch jobs, recipes, and products (similar to the source file detail page). Each of those three has the option to filter by batch_id.

Also, on both the batch detail page and each row of the batches table, display a completed recipes percentage (bar?) using batch.completed_recipe_count / batch.created_count * 100.0
