### ISSUE TITLE
Node UI Updates

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#823]
There have been updates to the nodes and status APIs. The following updates need to be done to the UI regarding nodes:

The /v4/status/ API has been deprecated in favor of a new redesigned /v5/status/ API. The new /v5/status/ API should return immediately and is updated approximately every 5 seconds. It provides a near-real time view of the scheduler status. If the new status API returns a 204, that means the scheduler is not available and there is no status info available. Sections of the UI below that rely on the status API should display some message explaining that the scheduler is offline.

There are new v5 versions of the node APIs, that basically remove some fields. The nodes status API does not exist in v5 (deprecated in favor of /v5/status/).

1. Change the overview page so that it now calls /v5/status/ instead of /v4/nodes/status/ (you can ajax every 5 seconds). The node display should display all active (is_active: true) nodes grouped by state. Use a single circle to group the nodes by their state title. Replace the "x of x nodes are healthy" heading with "x nodes" where x is the active node total.

2. Rework the nodes page to work entirely off of the /v5/status/ API, it can be ajaxed every 5 seconds. At the top level, split into two tabs: one for active nodes and one for inactive nodes. Each tab should have a table showing the applicable nodes (active vs inactive). We might want to remove the paging for the table since we have all of the data up front. Replace the entire right side ("Node Health" and "Status Overview") with the circle from the overview page with "x Nodes" above it. Clicking on a table row should take you to the node detail page as before.

The table columns are:
- Host: Allow sorting by this column. If in the active tab, there should be buttons for pausing, unpausing, and making the node inactive using the PATCH /v5/nodes/{id}/ API. Don't update the table based on the PATCH call, if anything changed it will be reflected in the next status ajax call. If in the inactive tab, there should just be one button for making the node active.
- State: displays the state title with rollover description, also displays some kind of icon if there is at least one error. If one error, the rollover text should be the error title, otherwise display the error count (e.g. "2 errors). Do the same for warnings with a different icon. Allowing filtering/sorting by state on this column (dropdown can just display all states returned from the API).
- Executions: display the total job executions for the node for the 4 categories: completed and failed in each of the three categories. Just do the total counts for each for now, I think the split by job type would be too much detail. The overall look to these 4 values could be similar to the job failure rates page. This could either be one whole column, or 4 separate columns. Use whatever looks best. We need some text somewhere explaining that these stats apply to the last 3 hours.
- Running: basically display the running jobs (like we have "Current Jobs" now). The /v5/status/ API contains job type info so you can get things like title and icon code. We might want to switch to a scheme where we only display each job type icon once and display the total number of jobs next to it.

3. Rework the node detail page to use the new /v5/node/{id}/ API. Update the table to only display the fields that come back from the v5 API. This page should also call the new /v5/status/ API every 5 seconds to get near-real-time information on the node (note that this node may not appear in the status API, if so just blank out any sections populated by it). Have a section at the top with hostname that displays the agent ID and state (title and description) from the status API. Have sections above the table for displaying the errors and warnings affecting the node (display title and description similar to job failure errors). I would also like to display all of the job execution info (running, completed, failed), but I'm not sure exactly how that should be formatted.

**Comment by wardcr** [comment]
I would suggest using one table for nodes with a visual indication of active/inactive (an icon/column/grayed out name, etc.) and then have a filter with inactive nodes hidden by default rather than two tabs.

**Comment by dfaller** [comment]
Still lurking I see! Yeah, that makes sense. A key thing is to hide inactive by default.
It is useful to know the number of inactive nodes up front, because if there are inactive nodes you often would like to make them active.

**Comment by ericsvendsen-mil** [comment]
Is there a v5 endpoint that reports the master/scheduler status as well as the system resources currently in use (cpu, memory, and disk)?

**Comment by dfaller** [comment]
Those will be added later to the new /v5/status/ API.

**Comment by ericsvendsen-mil** [comment]
Couple other questions about the new api:
* is there a set of predefined node states? e.g. ready, paused, offline, etc.
* you mentioned not needing pagination, but do you still want sorting and/or filtering?

**Comment by dfaller** [comment]
We have a hard-coded set of node states (which might change in the future), but it would be nice if the UI was just driven off of the JSON and didn't have hard-coded state knowledge. We'll start with that and see if we need state knowledge in the UI for something.

Yes, we want sorting/filtering since the number of nodes is theoretically unbounded. Note that each time the API is hit, nodes will "appear" and "disappear" from a particular set of filter criteria.

**Comment by ericsvendsen-mil** [comment]
Yes, the UI is driven off the JSON, however it'd be helpful for my static data to know some actual status values.

Regarding sorting/filtering - I just need to know if I can pass parameters to the API like the [current node endpoint](http://ngageoint.github.io/scale/docs/rest/node.html)

**Comment by dfaller** [comment]
Ah, no, there are no query parameters. It is one big JSON file.

**Comment by ericsvendsen-mil** [comment]
Ok that's fine - thanks.  One other question ... I'm not quite sure what you mean by this sentence:

> Executions: display the total job executions for the node for the 4 categories: completed and failed in each of the three categories.

Do you want to see the system, algorithm, data, and total errors? Or do you want to see totals for running, failed, and completed?  Or, perhaps something different that I'm not thinking of at the moment...

**Comment by dfaller** [comment]
4 columns:
number completed
number failed with algorithm error
number failed with data error
number failed with system error

**Comment by ericsvendsen-mil** [comment]
Here's the latest look at the nodes section.  Changes from this morning:
* Changed "Inactive" to "Deprecated"
* Updated pie chart labels when toggling between active/deprecated nodes
* Added pause and play buttons for each row in grid (with tooltips)
* Added "Active/Deprecated" breakdown underneath page title
* Increased width of Job Executions labels in grid
* Added errors and warnings boxes to details view
* Showing failed jobs breakdown in details view

I think the next step from here is to bring a build up and see what it looks like with real data.

![image](https://cloud.githubusercontent.com/assets/15909071/26368930/21a8ecfa-3fc1-11e7-8d05-4df95f423675.png)
![image](https://cloud.githubusercontent.com/assets/15909071/26368940/2854ffd0-3fc1-11e7-8252-b329e00ba815.png)
![image](https://cloud.githubusercontent.com/assets/15909071/26368946/2e230eb6-3fc1-11e7-8130-7e6ffc66ec07.png)

**Comment by dfaller** [comment]
Two comments on the node details page:

1. Could we make the job execution boxes a little bigger to make it easier to see the icons and counts? We have the available real estate to do that. Do the boxes wrap around if there are a large number of job types?

2. Could we add the "A few seconds ago", "2 hours ago", etc. type descriptions to all of the timestamps on the page? I think it's also good to include the literal timestamp; not sure how to best display them together. Also could we do a replace on the timestamps to remove the T to improve readability.

Do you have the latest master merged into your branch? If so, I could build your branch and deploy low side to give us a quick look integrated with Scale on "live" data.

**Comment by ericsvendsen-mil** [comment]
Addressed both of your comments with the latest commit.  Screenshot is below.

Yes, I just merged master into this branch so if you want to deploy it you can do so.  Just be aware that you'll need to change the local scaleConfig file to account for the new endpoint.  If you want only the new status endpoint to be `v5`, then do this:
```
"scaleConfigLocal": {
        "urls": {
            "apiPrefix": "/api/v4/",
            "overrides": {
                "nodeStatus": "/api/v5/"
            },
            ...
        },
        ...
    }
}
```

Otherwise, if you want all endpoints to use `v5` except for the old status endpoint that still drives the resource allocation reporting on the overview page, then do this:

```
{
    "scaleConfigLocal": {
        "urls": {
            "apiPrefix": "/api/v5/",
            "overrides": {
                "status": "/api/v4/"
            },
            ...
        },
        ...
    }
}

![image](https://cloud.githubusercontent.com/assets/15909071/26416774/06bd1f00-4085-11e7-82a4-9cad6563c346.png)

**Comment by dfaller** [comment]
Is the configuration not correct in the source? Why would I need to change it after build?
We want to use the second option by the way where everything but the old status API is on v5.

**Comment by ericsvendsen-mil** [comment]
I thought this was the sort of thing you handled with a local config, which isn't checked in to source control.  However I just committed the change to `scaleConfig.json`.  If you have any URL overrides in a local config you'll need to update those as I mentioned.

**Comment by dfaller** [comment]
Ok, I don't think we use anything like that anymore. Anything environment specific is handled through an env var passed to the Scale Docker image when it starts up as the web server.

**Comment by dfaller** [comment]
The change of "archived" to "deprecated" is now in master. You can update your branch now.
