### ISSUE TITLE
Source File Data UI

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#876]
First a bug fix: switch the ingest detail UI page to use /v4/sources/{id}/. The v5 version does not include the product information.

Create some new pages for viewing source file data.

1. Add a new left-hand menu item called "Data".
2. "Data" should take you to a page where you can view source files in a table (eventually we'll have tabs for product files and general files as well). The source file table:
  a. should use the /v5/sources/ REST API
  b. should display the following columns: file name, file size, data started, data ended, countries, last modified
  c. allow filtering on file name
  d. allow datetime filtering with some way to allow the user to pick between last modified (call it processing time?) and data time
3. Clicking on a source file in the table should take you to a source file detail page.
  a. This page should use the /v5/sources/{id}/ detail REST API to display the general fields in a nice way.
  b. Have a download link for the file if the URL field is provided
  c. Using tabs, have three different tables for showing the ingests, jobs, and products related to the source file. These tables should use the /v5/sources/{id}/ingests/, /v5/sources/{id}/jobs/, and /v5/sources/{id}/products/ REST APIs. The job table can have the same filtering options as the normal job table. The products table should display file_name, file_size, job column with job type name/version text that links to the job detail page, data started, data ended, countries, last modified.

**Comment by ericsvendsen-mil** [comment]
Notes:
* Print out country codes as a comma-delimited list
* Add first 10 columns of metadata on details page, then link to more if needed
* Add Countries to details page
* Link to workspace
* Make filesize and download more obvious
* Fix history issues so back button can be used

**Comment by dfaller** [comment]
Can we also go ahead and add the "2 days ago" stuff to the time stamps on the source file detail page? I think we should be consistent with timestamps on detail pages.

**Comment by ericsvendsen-mil** [comment]
Modified the timestamps as you requested and completed the items above.  Opened #888
