### ISSUE TITLE
Allow more advanced conditions on triggers

### ISSUE THREAD

**Issue by dickmanp** [ngageoint/scale#88]
Need to be able to support both AND and OR operators on triggers (and possibly more advanced combinations).  Currently if I want to run a recipe on 2 different data types, I have to create 2 different recipes that are exactly the same.

**Comment by dickmanp** [comment]
NOT operations would also be useful.  Jared could also use this functionality.

**Comment by dfaller** [comment]
Update both trigger JSONs (ingest and parse) to version 1.1 and accept two new fields under "condition":

"any_of_data_types" - optional array of strings that match the condition if the file has at least one of the data types in this array (must still match the "media_type" and "data_types" fields if provided for condition to match)
"not_data_types" - optional array of strings where the condition does not match if the file has at least one of the data types in this array

New JSON:
```
{
   "version": "1.1",
   "condition": {
      "media_type": "text/plain",
      "data_types": [
         "foo",
         "bar"
      ],
      "any_of_data_types": [
         "this_one",
         "or_this_one"
      ],
      "not_data_types": [
         "not_this_one",
         "nor_this_one"
      ]
   },
   "data": {
      "input_data_name": "my_file",
      "workspace_name": "my_workspace"
   }
}
```
