### ISSUE TITLE
Dynamic resource allocation for jobs

### ISSUE THREAD

**Issue by dickmanp** [ngageoint/scale#89]
Sometimes the amount of resources required to run a job will vary greatly based on the inputs to the job.  Currently resources are only specified at the job type level.

**Comment by dfaller** [comment]
Needs some thought and design work. One possibility is to have a special set of inputs to a job that reflects an ideal (or "up to") amount of resources. This also ties into the idea of having a potential range of resources when scheduling (required resources up to recommended resources).

**Comment by gisjedi** [comment]
I'm going to mark this a OBE now that we have resource multiplier support based on input data size.
