### ISSUE TITLE
Spaces in S3 path

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#926]
S3 has an odd behavior where spaces in an S3 path (key) are replaced with '+' characters, which then breaks the boto library's ability to download the file. Our current recommendation is to not use spaces in the S3 path. In the future with time permitting, we should see if there is a way Scale can work around this issue nicely.

**Comment by gisjedi** [comment]
The most annoying aspect of this is we are just attempting to retrieve files via the S3 object key given to us by the S3 event notification. If we can't rely on AWS to give us a key via _its own_ messaging system actually usable by _their own_ SDK (boto3), I fear for humanity.
