### ISSUE TITLE
Seed implementation roadmap 

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/scale#927]
We need to make a plan to fully support Seed compliant images. Our current Job Type interface needs to be analyzed for differences with the Seed interface specification.

**Comment by gisjedi** [comment]
Here is my initial understanding of what all needs to change for Seed to be fully supported by Scale:

- Update Scale to initially understand the Seed manifest. This would involve an entirely new Job Type like class for deserializing the entire label. The intention here is to move toward an entirely new code path so that we can support both the legacy Job Type interface (move toward deprecation) and Seed.
  - Create a REST API that is used for adding Seed jobs. This would be similar to the `/api/vX/job-types`
  - Create a REST API that could be used to discover Seed algorithms. This MAY need to be a separate project that works in concert with the Seed job-type API.
  - 
- For each inputData Update Scale pre to

**Comment by dfaller** [comment]
The roadmap for Seed has been well-defined at this point and transformed into the Seed project with all of the remaining issues.
