### ISSUE TITLE
Ingest Detail Page

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#935]
Rework the ingest detail page so it displays information related to the /v5/ingests/{id}/ REST API instead of information related to the associated source file.

**Comment by ericsvendsen-mil** [comment]
So I'm working this issue, as it's related to #1283. What would you like to see on this page other than just a list of attributes and their values?

![ingest-details](https://user-images.githubusercontent.com/15909071/45098209-83866f80-b0f2-11e8-996e-a8fe5b7e1b33.PNG)

**Comment by dfaller** [comment]
I would say that's sufficient for now, unless Chris wants something else. It might make more sense to add additional features to the equivalent future page in the new UI.
