### ISSUE TITLE
Add recipe completed status column to recipe view

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#94]
Please add the green "Completed X hours ago" status graphic from the "zoomed-in" recipe status to the "Recipe View" so a user can see if a recipe has completed successfully.

For extra points: Include if recipe is actively running, or blocked, or canceled, or pending!  That might involve a recursive query to all the jobs in the recipe which might be prove too expensive... but django might already be doing this in the api... I'm admittedly ignorant on the subject.

**Comment by dfaller** [comment]
We can't currently do the "extra points" but the main issue should be straight forward for the UI.
