### ISSUE TITLE
Missing NodeJS dependency http-parser-2.7

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale#943]
A NodeJS dependencies was added to the RedHat Base repository for 7.4, therefore it was removed from  EPEL. CentOS wont see those additions until 7.4 is released, which does not have a set release date yet.

**Comment by mikenholt** [comment]
Added hot-fix to scale/dockerfiles/framework/scale/env-shim.sh

**Comment by gisjedi** [comment]
Resolved in 866d855a2f7c394183303718748dd9124404b4b7
