### ISSUE TITLE
Add job type to elasticsearch logs 

### ISSUE THREAD

**Issue by mikenholt** [ngageoint/scale#948]
When debugging it would be ideal to have the job_type id associated with logs in elasticsearch to help pinpoint potential errors.

**Comment by gisjedi** [comment]
Job and JobType models can be found in `scale/job/models.py`

1. The JobType.id needs to be added as a tag where Docker parameters are applied in `job/configuration/configurators.py` under `_configure_all_tasks.py` roughly around line 285
2. Build of `scale` image and push to personal Docker Hub account.
3. Deploy into cluster and once all green, change `scale-logstash` service in Marathon to set `LOGSTASH_DEBUG` to true. This will redeploy the logstash service and the messages received can be seen in the STDOUT logs.
4. Once verified tags applied from step 1 are arriving, identify updates needed to the logstash config to extract JobType IDs.
5. The logging forwarder is responsible for pulling the data applied to the tags on the Docker container. This can be found in the `dockerfiles/logstash/logstash.conf-template` file.
6. The Logstash config can be quickly iterated on by using the `TEMPLATE_URI` environment variable to `scale-logstash` service. Hosting on https://gist.github.com is likely the quickest way to make that public accessible.
