### ISSUE TITLE
Minor recipe deatil view changes

### ISSUE THREAD

**Issue by cshamis** [ngageoint/scale#95]
Add a legend to indicate what green ,red, purple, grey and blue mean.

Also, can we make the running blue block "pulse" so as to indicate some kind of activity is occurring?

Also, consider changing the "RUNNING" or "COMPLETED" or "PENDING" buttons in the job description on the right hand side into a button to encourage user to click on it.  It's not immediately obvious that it is a link to the job detail page.

**Comment by dfaller** [comment]
I had a related issue in our old backlog to add icons to the colors to help describe the statuses.

For the job detail link, I think using the job type name for the link (instead of the status) is a more obvious job link for the user.
