### ISSUE TITLE
Fix job type creation

### ISSUE THREAD

**Issue by dfaller** [ngageoint/scale#966]
Right now job type creation fails with null constraint errors if fields like error mapping are not provided. Fix the JobTypeManager.create_job_type() method to create blank JSON fields for non-nullable JSON fields like error_mapping.

**Comment by mikenholt** [comment]
This issue was created based off of Clint trying to validate and update a new job-type.  The error he was seeing was: 
```
IntegrityError: null value in column "error_mapping" violates not-null constraint
```
I was unable to repeat this error using many different job-type submissions to Scale and in talking to Clint he believes the issue was something outside Scale.
